version: "3.7"
services:
  database:
    image: postgres:13.0
    container_name: digilog-postgres
    restart: always
    ports:
      - 5500:5432
    environment:
      POSTGRES_SERVICE_HOST: digilog-postgres
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_USER: digilog
      POSTGRES_DB: digilog
    depends_on:
      - fluentd      
    volumes:
      - postgresdata:/var/lib/postgresql/data
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "postgres-db"
    
  flyway:
    build:
      context: ./flyway/.
      target: dev
    image: digilog-flyway
    container_name: digilog-flyway
    environment:
      POSTGRES_SERVICE_HOST: digilog-postgres
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_USER: digilog
      POSTGRES_DB: digilog
    volumes:
      - ./flyway/flywaymigrations:/flyway/sql
    depends_on:
      - database
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "flyway"
  
  mongo:
    image: mongo:5.0.9
    container_name: digilog-mongodb
    restart: always
    ports:
      - 5550:27017
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongopwd
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "mongo-db"
  
  fluentd:
    build: ./fluentd
    container_name: digilog-fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    depends_on:
      - elasticsearch      

  elasticsearch:      
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.2
    container_name: digilog-elasticsearch
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.2
    container_name: digilog-kibana
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  web:
    build:
      context: ./web/.
      target: dev
    image: digilogweb3
    container_name: digilog-web
    restart: always
    environment:
      POSTGRES_SERVICE_HOST: digilog-postgres
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_USER: digilog
      POSTGRES_DB: digilog
      MONGODB_SERVICE_HOST: digilog-mongodb
      MONGODB_SERVICE_PORT: 27017
      MONGODB_PASSWORD: mongopwd
      MONGODB_USER: root
    ports:
      - 80:5000
      - 5000:5000
    volumes:
      - ./web/app/webapp:/home/digilog/webapp
      - type: bind
        source: ./web/gunicorn.conf.py
        target: /etc/gunicorn.conf.py
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "web"

  queueprocessor:
    build: 
      context: ./scrapy/.
      target: dev
    image: scrapy
    container_name: digilog-crawl-queue-processor
    environment:
      POSTGRES_SERVICE_HOST: digilog-postgres
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_USER: digilog
      POSTGRES_DB: digilog
      MONGODB_SERVICE_HOST: digilog-mongodb
      MONGODB_SERVICE_PORT: 27017
      MONGODB_PASSWORD: mongopwd
      MONGODB_USER: root
    entrypoint: ["python"]
    command: ["/src/queue_processor.py"]
    restart: always
    volumes:
    - ./scrapy/digilog:/src
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "crawl-queue-processor"

  queueprocessoranalysis:
    build:
      context: ./analysis/.
      target: dev
    image: analysis_queued
    container_name: digilog-analysis-queue-processor
    environment:
      POSTGRES_SERVICE_HOST: digilog-postgres
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_USER: digilog
      POSTGRES_DB: digilog
      MONGODB_SERVICE_HOST: digilog-mongodb
      MONGODB_SERVICE_PORT: 27017
      MONGODB_PASSWORD: mongopwd
      MONGODB_USER: root
    entrypoint: ["python"]
    command: ["/src/queue_analysis.py"]
    restart: always
    volumes:
    - ./analysis:/src

  scheduler:
    build:
      context: ./scheduler/.
      target: dev
    image: scheduler
    container_name: digilog-scheduler
    environment:
      POSTGRES_SERVICE_HOST: digilog-postgres
      POSTGRES_SERVICE_PORT: 5432
      POSTGRES_PASSWORD: password
      POSTGRES_USER: digilog
      POSTGRES_DB: digilog
      MONGODB_SERVICE_HOST: digilog-mongodb
      MONGODB_SERVICE_PORT: 27017
      MONGODB_PASSWORD: mongopwd
      MONGODB_USER: root
    restart: on-failure
    volumes:
      - ./scheduler/src:/usr/src
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: "crawl-queue-processor"


volumes:
  esdata:
    driver: local
    name: digilog-volume-elasticsearch
  postgresdata:
    driver: local
    name: digilog-volume-flyway
  mongodbdata:
    driver: local
    name: digilog-volume-mongodb

networks:
  default:
    name: digilog-data-network
