INSERT INTO digilog.municipality (name_de, url, state_id)
SELECT m.name as name_de, '' as url, state.id as state_id
FROM (
         VALUES ('Kappel am Albis', 'Zürich'),
                ('Knonau', 'Zürich'),
                ('Maschwanden', 'Zürich'),
                ('Mettmenstetten', 'Zürich'),
                ('Obfelden', 'Zürich'),
                ('Ottenbach', 'Zürich'),
                ('Rifferswil', 'Zürich'),
                ('Stallikon', 'Zürich'),
                ('Wettswil am Albis', 'Zürich'),
                ('Adlikon', 'Zürich'),
                ('Benken (ZH)', 'Zürich'),
                ('Berg am Irchel', 'Zürich'),
                ('Buch am Irchel', 'Zürich'),
                ('Dachsen', 'Zürich'),
                ('Dorf', 'Zürich'),
                ('Feuerthalen', 'Zürich'),
                ('Flaach', 'Zürich'),
                ('Flurlingen', 'Zürich'),
                ('Andelfingen', 'Zürich'),
                ('Henggart', 'Zürich'),
                ('Humlikon', 'Zürich'),
                ('Kleinandelfingen', 'Zürich'),
                ('Laufen-Uhwiesen', 'Zürich'),
                ('Marthalen', 'Zürich'),
                ('Ossingen', 'Zürich'),
                ('Rheinau', 'Zürich'),
                ('Thalheim an der Thur', 'Zürich'),
                ('Trüllikon', 'Zürich'),
                ('Truttikon', 'Zürich'),
                ('Volken', 'Zürich'),
                ('Bachenbülach', 'Zürich'),
                ('Bassersdorf', 'Zürich'),
                ('Bülach', 'Zürich'),
                ('Dietlikon', 'Zürich'),
                ('Eglisau', 'Zürich'),
                ('Embrach', 'Zürich'),
                ('Freienstein-Teufen', 'Zürich'),
                ('Glattfelden', 'Zürich'),
                ('Hochfelden', 'Zürich'),
                ('Höri', 'Zürich'),
                ('Hüntwangen', 'Zürich'),
                ('Kloten', 'Zürich'),
                ('Lufingen', 'Zürich'),
                ('Nürensdorf', 'Zürich'),
                ('Oberembrach', 'Zürich'),
                ('Opfikon', 'Zürich'),
                ('Rafz', 'Zürich'),
                ('Rorbas', 'Zürich'),
                ('Wallisellen', 'Zürich'),
                ('Wasterkingen', 'Zürich'),
                ('Wil (ZH)', 'Zürich'),
                ('Winkel', 'Zürich'),
                ('Bachs', 'Zürich'),
                ('Boppelsen', 'Zürich'),
                ('Buchs (ZH)', 'Zürich'),
                ('Dällikon', 'Zürich'),
                ('Dänikon', 'Zürich'),
                ('Dielsdorf', 'Zürich'),
                ('Hüttikon', 'Zürich'),
                ('Neerach', 'Zürich'),
                ('Niederglatt', 'Zürich'),
                ('Niederhasli', 'Zürich'),
                ('Niederweningen', 'Zürich'),
                ('Oberglatt', 'Zürich'),
                ('Oberweningen', 'Zürich'),
                ('Otelfingen', 'Zürich'),
                ('Regensberg', 'Zürich'),
                ('Regensdorf', 'Zürich'),
                ('Rümlang', 'Zürich'),
                ('Schleinikon', 'Zürich'),
                ('Schöfflisdorf', 'Zürich'),
                ('Stadel', 'Zürich'),
                ('Steinmaur', 'Zürich'),
                ('Weiach', 'Zürich'),
                ('Bäretswil', 'Zürich'),
                ('Bubikon', 'Zürich'),
                ('Dürnten', 'Zürich'),
                ('Fischenthal', 'Zürich'),
                ('Gossau (ZH)', 'Zürich'),
                ('Grüningen', 'Zürich'),
                ('Hinwil', 'Zürich'),
                ('Rüti (ZH)', 'Zürich'),
                ('Seegräben', 'Zürich'),
                ('Wald (ZH)', 'Zürich'),
                ('Wetzikon (ZH)', 'Zürich'),
                ('Adliswil', 'Zürich'),
                ('Kilchberg (ZH)', 'Zürich'),
                ('Langnau am Albis', 'Zürich'),
                ('Oberrieden', 'Zürich'),
                ('Richterswil', 'Zürich'),
                ('Rüschlikon', 'Zürich'),
                ('Thalwil', 'Zürich'),
                ('Erlenbach (ZH)', 'Zürich'),
                ('Herrliberg', 'Zürich'),
                ('Hombrechtikon', 'Zürich'),
                ('Küsnacht (ZH)', 'Zürich'),
                ('Männedorf', 'Zürich'),
                ('Meilen', 'Zürich'),
                ('Oetwil am See', 'Zürich'),
                ('Stäfa', 'Zürich'),
                ('Uetikon am See', 'Zürich'),
                ('Zumikon', 'Zürich'),
                ('Zollikon', 'Zürich'),
                ('Fehraltorf', 'Zürich'),
                ('Hittnau', 'Zürich'),
                ('Lindau', 'Zürich'),
                ('Pfäffikon', 'Zürich'),
                ('Russikon', 'Zürich'),
                ('Weisslingen', 'Zürich'),
                ('Wila', 'Zürich'),
                ('Wildberg', 'Zürich'),
                ('Dübendorf', 'Zürich'),
                ('Egg', 'Zürich'),
                ('Fällanden', 'Zürich'),
                ('Greifensee', 'Zürich'),
                ('Maur', 'Zürich'),
                ('Mönchaltorf', 'Zürich'),
                ('Schwerzenbach', 'Zürich'),
                ('Uster', 'Zürich'),
                ('Volketswil', 'Zürich'),
                ('Wangen-Brüttisellen', 'Zürich'),
                ('Altikon', 'Zürich'),
                ('Brütten', 'Zürich'),
                ('Dägerlen', 'Zürich'),
                ('Dättlikon', 'Zürich'),
                ('Dinhard', 'Zürich'),
                ('Ellikon an der Thur', 'Zürich'),
                ('Elsau', 'Zürich'),
                ('Hagenbuch', 'Zürich'),
                ('Hettlingen', 'Zürich'),
                ('Neftenbach', 'Zürich'),
                ('Pfungen', 'Zürich'),
                ('Rickenbach (ZH)', 'Zürich'),
                ('Schlatt (ZH)', 'Zürich'),
                ('Seuzach', 'Zürich'),
                ('Turbenthal', 'Zürich'),
                ('Winterthur', 'Zürich'),
                ('Zell (ZH)', 'Zürich'),
                ('Aesch (ZH)', 'Zürich'),
                ('Birmensdorf (ZH)', 'Zürich'),
                ('Dietikon', 'Zürich'),
                ('Geroldswil', 'Zürich'),
                ('Oberengstringen', 'Zürich'),
                ('Oetwil an der Limmat', 'Zürich'),
                ('Schlieren', 'Zürich'),
                ('Uitikon', 'Zürich'),
                ('Unterengstringen', 'Zürich'),
                ('Urdorf', 'Zürich'),
                ('Weiningen (ZH)', 'Zürich'),
                ('Zürich', 'Zürich'),
                ('Stammheim', 'Zürich'),
                ('Wädenswil', 'Zürich'),
                ('Elgg', 'Zürich'),
                ('Horgen', 'Zürich'),
                ('Illnau-Effretikon', 'Zürich'),
                ('Bauma', 'Zürich'),
                ('Wiesendangen', 'Zürich'),
                ('Aarberg', 'Bern'),
                ('Bargen (BE)', 'Bern'),
                ('Grossaffoltern', 'Bern'),
                ('Kallnach', 'Bern'),
                ('Kappelen', 'Bern'),
                ('Lyss', 'Bern'),
                ('Meikirch', 'Bern'),
                ('Radelfingen', 'Bern'),
                ('Rapperswil (BE)', 'Bern'),
                ('Schüpfen', 'Bern'),
                ('Seedorf (BE)', 'Bern'),
                ('Aarwangen', 'Bern'),
                ('Auswil', 'Bern'),
                ('Bannwil', 'Bern'),
                ('Bleienbach', 'Bern'),
                ('Busswil bei Melchnau', 'Bern'),
                ('Gondiswil', 'Bern'),
                ('Langenthal', 'Bern'),
                ('Lotzwil', 'Bern'),
                ('Madiswil', 'Bern'),
                ('Melchnau', 'Bern'),
                ('Oeschenbach', 'Bern'),
                ('Reisiswil', 'Bern'),
                ('Roggwil (BE)', 'Bern'),
                ('Rohrbach', 'Bern'),
                ('Rohrbachgraben', 'Bern'),
                ('Rütschelen', 'Bern'),
                ('Schwarzhäusern', 'Bern'),
                ('Thunstetten', 'Bern'),
                ('Ursenbach', 'Bern'),
                ('Wynau', 'Bern'),
                ('Bern', 'Bern'),
                ('Bolligen', 'Bern'),
                ('Bremgarten bei Bern', 'Bern'),
                ('Kirchlindach', 'Bern'),
                ('Köniz', 'Bern'),
                ('Muri bei Bern', 'Bern'),
                ('Oberbalm', 'Bern'),
                ('Stettlen', 'Bern'),
                ('Vechigen', 'Bern'),
                ('Wohlen bei Bern', 'Bern'),
                ('Zollikofen', 'Bern'),
                ('Ittigen', 'Bern'),
                ('Ostermundigen', 'Bern'),
                ('Biel/Bienne', 'Bern'),
                ('Evilard', 'Bern'),
                ('Arch', 'Bern'),
                ('Büetigen', 'Bern'),
                ('Büren an der Aare', 'Bern'),
                ('Diessbach bei Büren', 'Bern'),
                ('Dotzigen', 'Bern'),
                ('Lengnau (BE)', 'Bern'),
                ('Leuzigen', 'Bern'),
                ('Meienried', 'Bern'),
                ('Meinisberg', 'Bern'),
                ('Oberwil bei Büren', 'Bern'),
                ('Pieterlen', 'Bern'),
                ('Rüti bei Büren', 'Bern'),
                ('Wengi', 'Bern'),
                ('Aefligen', 'Bern'),
                ('Alchenstorf', 'Bern'),
                ('Bäriswil', 'Bern'),
                ('Burgdorf', 'Bern'),
                ('Ersigen', 'Bern'),
                ('Hasle bei Burgdorf', 'Bern'),
                ('Heimiswil', 'Bern'),
                ('Hellsau', 'Bern'),
                ('Hindelbank', 'Bern'),
                ('Höchstetten', 'Bern'),
                ('Kernenried', 'Bern'),
                ('Kirchberg (BE)', 'Bern'),
                ('Koppigen', 'Bern'),
                ('Krauchthal', 'Bern'),
                ('Lyssach', 'Bern'),
                ('Oberburg', 'Bern'),
                ('Rüdtligen-Alchenflüh', 'Bern'),
                ('Rumendingen', 'Bern'),
                ('Rüti bei Lyssach', 'Bern'),
                ('Willadingen', 'Bern'),
                ('Wynigen', 'Bern'),
                ('Corgémont', 'Bern'),
                ('Cormoret', 'Bern'),
                ('Cortébert', 'Bern'),
                ('Courtelary', 'Bern'),
                ('La Ferrière', 'Bern'),
                ('Mont-Tramelan', 'Bern'),
                ('Orvin', 'Bern'),
                ('Renan (BE)', 'Bern'),
                ('Romont (BE)', 'Bern'),
                ('Saint-Imier', 'Bern'),
                ('Sonceboz-Sombeval', 'Bern'),
                ('Sonvilier', 'Bern'),
                ('Tramelan', 'Bern'),
                ('Villeret', 'Bern'),
                ('Sauge', 'Bern'),
                ('Péry-La Heutte', 'Bern'),
                ('Brüttelen', 'Bern'),
                ('Erlach', 'Bern'),
                ('Finsterhennen', 'Bern'),
                ('Gals', 'Bern'),
                ('Gampelen', 'Bern'),
                ('Ins', 'Bern'),
                ('Lüscherz', 'Bern'),
                ('Müntschemier', 'Bern'),
                ('Siselen', 'Bern'),
                ('Treiten', 'Bern'),
                ('Tschugg', 'Bern'),
                ('Vinelz', 'Bern'),
                ('Bätterkinden', 'Bern'),
                ('Deisswil bei Münchenbuchsee', 'Bern'),
                ('Diemerswil', 'Bern'),
                ('Fraubrunnen', 'Bern'),
                ('Jegenstorf', 'Bern'),
                ('Iffwil', 'Bern'),
                ('Mattstetten', 'Bern'),
                ('Moosseedorf', 'Bern'),
                ('Münchenbuchsee', 'Bern'),
                ('Urtenen-Schönbühl', 'Bern'),
                ('Utzenstorf', 'Bern'),
                ('Wiggiswil', 'Bern'),
                ('Wiler bei Utzenstorf', 'Bern'),
                ('Zielebach', 'Bern'),
                ('Zuzwil (BE)', 'Bern'),
                ('Adelboden', 'Bern'),
                ('Aeschi bei Spiez', 'Bern'),
                ('Frutigen', 'Bern'),
                ('Kandergrund', 'Bern'),
                ('Kandersteg', 'Bern'),
                ('Krattigen', 'Bern'),
                ('Reichenbach im Kandertal', 'Bern'),
                ('Beatenberg', 'Bern'),
                ('Bönigen', 'Bern'),
                ('Brienz (BE)', 'Bern'),
                ('Brienzwiler', 'Bern'),
                ('Därligen', 'Bern'),
                ('Grindelwald', 'Bern'),
                ('Gsteigwiler', 'Bern'),
                ('Gündlischwand', 'Bern'),
                ('Habkern', 'Bern'),
                ('Hofstetten bei Brienz', 'Bern'),
                ('Interlaken', 'Bern'),
                ('Iseltwald', 'Bern'),
                ('Lauterbrunnen', 'Bern'),
                ('Leissigen', 'Bern'),
                ('Lütschental', 'Bern'),
                ('Matten bei Interlaken', 'Bern'),
                ('Niederried bei Interlaken', 'Bern'),
                ('Oberried am Brienzersee', 'Bern'),
                ('Ringgenberg (BE)', 'Bern'),
                ('Saxeten', 'Bern'),
                ('Schwanden bei Brienz', 'Bern'),
                ('Unterseen', 'Bern'),
                ('Wilderswil', 'Bern'),
                ('Arni (BE)', 'Bern'),
                ('Biglen', 'Bern'),
                ('Bowil', 'Bern'),
                ('Brenzikofen', 'Bern'),
                ('Freimettigen', 'Bern'),
                ('Grosshöchstetten', 'Bern'),
                ('Häutligen', 'Bern'),
                ('Herbligen', 'Bern'),
                ('Kiesen', 'Bern'),
                ('Konolfingen', 'Bern'),
                ('Landiswil', 'Bern'),
                ('Linden', 'Bern'),
                ('Mirchel', 'Bern'),
                ('Münsingen', 'Bern'),
                ('Niederhünigen', 'Bern'),
                ('Oberdiessbach', 'Bern'),
                ('Oberthal', 'Bern'),
                ('Oppligen', 'Bern'),
                ('Rubigen', 'Bern'),
                ('Walkringen', 'Bern'),
                ('Worb', 'Bern'),
                ('Zäziwil', 'Bern'),
                ('Oberhünigen', 'Bern'),
                ('Allmendingen', 'Bern'),
                ('Wichtrach', 'Bern'),
                ('Ferenbalm', 'Bern'),
                ('Frauenkappelen', 'Bern'),
                ('Gurbrü', 'Bern'),
                ('Kriechenwil', 'Bern'),
                ('Laupen', 'Bern'),
                ('Mühleberg', 'Bern'),
                ('Münchenwiler', 'Bern'),
                ('Neuenegg', 'Bern'),
                ('Wileroltigen', 'Bern'),
                ('Belprahon', 'Bern'),
                ('Champoz', 'Bern'),
                ('Corcelles (BE)', 'Bern'),
                ('Court', 'Bern'),
                ('Crémines', 'Bern'),
                ('Eschert', 'Bern'),
                ('Grandval', 'Bern'),
                ('Loveresse', 'Bern'),
                ('Moutier', 'Bern'),
                ('Perrefitte', 'Bern'),
                ('Reconvilier', 'Bern'),
                ('Roches (BE)', 'Bern'),
                ('Saicourt', 'Bern'),
                ('Saules (BE)', 'Bern'),
                ('Schelten', 'Bern'),
                ('Seehof', 'Bern'),
                ('Sorvilier', 'Bern'),
                ('Tavannes', 'Bern'),
                ('Rebévelier', 'Bern'),
                ('Petit-Val', 'Bern'),
                ('Valbirse', 'Bern'),
                ('La Neuveville', 'Bern'),
                ('Nods', 'Bern'),
                ('Plateau de Diesse', 'Bern'),
                ('Aegerten', 'Bern'),
                ('Bellmund', 'Bern'),
                ('Brügg', 'Bern'),
                ('Bühl', 'Bern'),
                ('Epsach', 'Bern'),
                ('Hagneck', 'Bern'),
                ('Hermrigen', 'Bern'),
                ('Jens', 'Bern'),
                ('Ipsach', 'Bern'),
                ('Ligerz', 'Bern'),
                ('Merzligen', 'Bern'),
                ('Mörigen', 'Bern'),
                ('Nidau', 'Bern'),
                ('Orpund', 'Bern'),
                ('Port', 'Bern'),
                ('Safnern', 'Bern'),
                ('Scheuren', 'Bern'),
                ('Schwadernau', 'Bern'),
                ('Studen (BE)', 'Bern'),
                ('Sutz-Lattrigen', 'Bern'),
                ('Täuffelen', 'Bern'),
                ('Walperswil', 'Bern'),
                ('Worben', 'Bern'),
                ('Twann-Tüscherz', 'Bern'),
                ('Därstetten', 'Bern'),
                ('Diemtigen', 'Bern'),
                ('Erlenbach im Simmental', 'Bern'),
                ('Oberwil im Simmental', 'Bern'),
                ('Reutigen', 'Bern'),
                ('Spiez', 'Bern'),
                ('Wimmis', 'Bern'),
                ('Stocken-Höfen', 'Bern'),
                ('Guttannen', 'Bern'),
                ('Hasliberg', 'Bern'),
                ('Innertkirchen', 'Bern'),
                ('Meiringen', 'Bern'),
                ('Schattenhalb', 'Bern'),
                ('Boltigen', 'Bern'),
                ('Lenk', 'Bern'),
                ('St. Stephan', 'Bern'),
                ('Zweisimmen', 'Bern'),
                ('Gsteig', 'Bern'),
                ('Lauenen', 'Bern'),
                ('Saanen', 'Bern'),
                ('Guggisberg', 'Bern'),
                ('Rüschegg', 'Bern'),
                ('Schwarzenburg', 'Bern'),
                ('Belp', 'Bern'),
                ('Burgistein', 'Bern'),
                ('Gerzensee', 'Bern'),
                ('Gurzelen', 'Bern'),
                ('Jaberg', 'Bern'),
                ('Kaufdorf', 'Bern'),
                ('Kehrsatz', 'Bern'),
                ('Kirchdorf (BE)', 'Bern'),
                ('Niedermuhlern', 'Bern'),
                ('Riggisberg', 'Bern'),
                ('Rüeggisberg', 'Bern'),
                ('Seftigen', 'Bern'),
                ('Toffen', 'Bern'),
                ('Uttigen', 'Bern'),
                ('Wattenwil', 'Bern'),
                ('Wald (BE)', 'Bern'),
                ('Thurnen', 'Bern'),
                ('Eggiwil', 'Bern'),
                ('Langnau im Emmental', 'Bern'),
                ('Lauperswil', 'Bern'),
                ('Röthenbach im Emmental', 'Bern'),
                ('Rüderswil', 'Bern'),
                ('Schangnau', 'Bern'),
                ('Signau', 'Bern'),
                ('Trub', 'Bern'),
                ('Trubschachen', 'Bern'),
                ('Amsoldingen', 'Bern'),
                ('Blumenstein', 'Bern'),
                ('Buchholterberg', 'Bern'),
                ('Eriz', 'Bern'),
                ('Fahrni', 'Bern'),
                ('Heiligenschwendi', 'Bern'),
                ('Heimberg', 'Bern'),
                ('Hilterfingen', 'Bern'),
                ('Homberg', 'Bern'),
                ('Horrenbach-Buchen', 'Bern'),
                ('Oberhofen am Thunersee', 'Bern'),
                ('Oberlangenegg', 'Bern'),
                ('Pohlern', 'Bern'),
                ('Sigriswil', 'Bern'),
                ('Steffisburg', 'Bern'),
                ('Teuffenthal (BE)', 'Bern'),
                ('Thierachern', 'Bern'),
                ('Thun', 'Bern'),
                ('Uebeschi', 'Bern'),
                ('Uetendorf', 'Bern'),
                ('Unterlangenegg', 'Bern'),
                ('Wachseldorn', 'Bern'),
                ('Zwieselberg', 'Bern'),
                ('Forst-Längenbühl', 'Bern'),
                ('Affoltern im Emmental', 'Bern'),
                ('Dürrenroth', 'Bern'),
                ('Eriswil', 'Bern'),
                ('Huttwil', 'Bern'),
                ('Lützelflüh', 'Bern'),
                ('Rüegsau', 'Bern'),
                ('Sumiswald', 'Bern'),
                ('Trachselwald', 'Bern'),
                ('Walterswil (BE)', 'Bern'),
                ('Wyssachen', 'Bern'),
                ('Attiswil', 'Bern'),
                ('Berken', 'Bern'),
                ('Bettenhausen', 'Bern'),
                ('Farnern', 'Bern'),
                ('Graben', 'Bern'),
                ('Heimenhausen', 'Bern'),
                ('Herzogenbuchsee', 'Bern'),
                ('Inkwil', 'Bern'),
                ('Niederbipp', 'Bern'),
                ('Niederönz', 'Bern'),
                ('Oberbipp', 'Bern'),
                ('Ochlenberg', 'Bern'),
                ('Rumisberg', 'Bern'),
                ('Seeberg', 'Bern'),
                ('Thörigen', 'Bern'),
                ('Walliswil bei Niederbipp', 'Bern'),
                ('Walliswil bei Wangen', 'Bern'),
                ('Wangen an der Aare', 'Bern'),
                ('Wangenried', 'Bern'),
                ('Wiedlisbach', 'Bern'),
                ('Doppleschwand', 'Luzern'),
                ('Entlebuch', 'Luzern'),
                ('Flühli', 'Luzern'),
                ('Hasle (LU)', 'Luzern'),
                ('Romoos', 'Luzern'),
                ('Schüpfheim', 'Luzern'),
                ('Werthenstein', 'Luzern'),
                ('Escholzmatt-Marbach', 'Luzern'),
                ('Aesch (LU)', 'Luzern'),
                ('Ballwil', 'Luzern'),
                ('Emmen', 'Luzern'),
                ('Ermensee', 'Luzern'),
                ('Eschenbach (LU)', 'Luzern'),
                ('Hitzkirch', 'Luzern'),
                ('Hochdorf', 'Luzern'),
                ('Hohenrain', 'Luzern'),
                ('Inwil', 'Luzern'),
                ('Rain', 'Luzern'),
                ('Römerswil', 'Luzern'),
                ('Rothenburg', 'Luzern'),
                ('Schongau', 'Luzern'),
                ('Adligenswil', 'Luzern'),
                ('Buchrain', 'Luzern'),
                ('Dierikon', 'Luzern'),
                ('Ebikon', 'Luzern'),
                ('Gisikon', 'Luzern'),
                ('Greppen', 'Luzern'),
                ('Honau', 'Luzern'),
                ('Horw', 'Luzern'),
                ('Kriens', 'Luzern'),
                ('Luzern', 'Luzern'),
                ('Malters', 'Luzern'),
                ('Meggen', 'Luzern'),
                ('Meierskappel', 'Luzern'),
                ('Root', 'Luzern'),
                ('Schwarzenberg', 'Luzern'),
                ('Udligenswil', 'Luzern'),
                ('Vitznau', 'Luzern'),
                ('Weggis', 'Luzern'),
                ('Beromünster', 'Luzern'),
                ('Büron', 'Luzern'),
                ('Buttisholz', 'Luzern'),
                ('Eich', 'Luzern'),
                ('Geuensee', 'Luzern'),
                ('Grosswangen', 'Luzern'),
                ('Hildisrieden', 'Luzern'),
                ('Knutwil', 'Luzern'),
                ('Mauensee', 'Luzern'),
                ('Neuenkirch', 'Luzern'),
                ('Nottwil', 'Luzern'),
                ('Oberkirch', 'Luzern'),
                ('Rickenbach (LU)', 'Luzern'),
                ('Ruswil', 'Luzern'),
                ('Schenkon', 'Luzern'),
                ('Schlierbach', 'Luzern'),
                ('Sempach', 'Luzern'),
                ('Sursee', 'Luzern'),
                ('Triengen', 'Luzern'),
                ('Wolhusen', 'Luzern'),
                ('Alberswil', 'Luzern'),
                ('Altbüron', 'Luzern'),
                ('Altishofen', 'Luzern'),
                ('Dagmersellen', 'Luzern'),
                ('Egolzwil', 'Luzern'),
                ('Ettiswil', 'Luzern'),
                ('Fischbach', 'Luzern'),
                ('Grossdietwil', 'Luzern'),
                ('Hergiswil bei Willisau', 'Luzern'),
                ('Luthern', 'Luzern'),
                ('Menznau', 'Luzern'),
                ('Nebikon', 'Luzern'),
                ('Pfaffnau', 'Luzern'),
                ('Reiden', 'Luzern'),
                ('Roggliswil', 'Luzern'),
                ('Schötz', 'Luzern'),
                ('Ufhusen', 'Luzern'),
                ('Wauwil', 'Luzern'),
                ('Wikon', 'Luzern'),
                ('Zell (LU)', 'Luzern'),
                ('Willisau', 'Luzern'),
                ('Altdorf (UR)', 'Uri'),
                ('Andermatt', 'Uri'),
                ('Attinghausen', 'Uri'),
                ('Bürglen (UR)', 'Uri'),
                ('Erstfeld', 'Uri'),
                ('Flüelen', 'Uri'),
                ('Göschenen', 'Uri'),
                ('Gurtnellen', 'Uri'),
                ('Hospental', 'Uri'),
                ('Isenthal', 'Uri'),
                ('Realp', 'Uri'),
                ('Schattdorf', 'Uri'),
                ('Seedorf (UR)', 'Uri'),
                ('Seelisberg', 'Uri'),
                ('Silenen', 'Uri'),
                ('Sisikon', 'Uri'),
                ('Spiringen', 'Uri'),
                ('Unterschächen', 'Uri'),
                ('Wassen', 'Uri'),
                ('Einsiedeln', 'Schwyz'),
                ('Gersau', 'Schwyz'),
                ('Feusisberg', 'Schwyz'),
                ('Freienbach', 'Schwyz'),
                ('Wollerau', 'Schwyz'),
                ('Küssnacht (SZ)', 'Schwyz'),
                ('Altendorf', 'Schwyz'),
                ('Galgenen', 'Schwyz'),
                ('Innerthal', 'Schwyz'),
                ('Lachen', 'Schwyz'),
                ('Reichenburg', 'Schwyz'),
                ('Schübelbach', 'Schwyz'),
                ('Tuggen', 'Schwyz'),
                ('Vorderthal', 'Schwyz'),
                ('Wangen (SZ)', 'Schwyz'),
                ('Alpthal', 'Schwyz'),
                ('Arth', 'Schwyz'),
                ('Illgau', 'Schwyz'),
                ('Ingenbohl', 'Schwyz'),
                ('Lauerz', 'Schwyz'),
                ('Morschach', 'Schwyz'),
                ('Muotathal', 'Schwyz'),
                ('Oberiberg', 'Schwyz'),
                ('Riemenstalden', 'Schwyz'),
                ('Rothenthurm', 'Schwyz'),
                ('Sattel', 'Schwyz'),
                ('Schwyz', 'Schwyz'),
                ('Steinen', 'Schwyz'),
                ('Steinerberg', 'Schwyz'),
                ('Unteriberg', 'Schwyz'),
                ('Alpnach', 'Obwalden'),
                ('Engelberg', 'Obwalden'),
                ('Giswil', 'Obwalden'),
                ('Kerns', 'Obwalden'),
                ('Lungern', 'Obwalden'),
                ('Sachseln', 'Obwalden'),
                ('Sarnen', 'Obwalden'),
                ('Beckenried', 'Nidwalden'),
                ('Buochs', 'Nidwalden'),
                ('Dallenwil', 'Nidwalden'),
                ('Emmetten', 'Nidwalden'),
                ('Ennetbürgen', 'Nidwalden'),
                ('Ennetmoos', 'Nidwalden'),
                ('Hergiswil (NW)', 'Nidwalden'),
                ('Oberdorf (NW)', 'Nidwalden'),
                ('Stans', 'Nidwalden'),
                ('Stansstad', 'Nidwalden'),
                ('Wolfenschiessen', 'Nidwalden'),
                ('Glarus Nord', 'Glarus'),
                ('Glarus Süd', 'Glarus'),
                ('Glarus', 'Glarus'),
                ('Baar', 'Zug'),
                ('Cham', 'Zug'),
                ('Hünenberg', 'Zug'),
                ('Menzingen', 'Zug'),
                ('Neuheim', 'Zug'),
                ('Oberägeri', 'Zug'),
                ('Risch', 'Zug'),
                ('Steinhausen', 'Zug'),
                ('Unterägeri', 'Zug'),
                ('Walchwil', 'Zug'),
                ('Zug', 'Zug'),
                ('Châtillon (FR)', 'Fribourg'),
                ('Cugy (FR)', 'Fribourg'),
                ('Fétigny', 'Fribourg'),
                ('Gletterens', 'Fribourg'),
                ('Lully (FR)', 'Fribourg'),
                ('Ménières', 'Fribourg'),
                ('Montagny (FR)', 'Fribourg'),
                ('Nuvilly', 'Fribourg'),
                ('Prévondavaux', 'Fribourg'),
                ('Saint-Aubin (FR)', 'Fribourg'),
                ('Sévaz', 'Fribourg'),
                ('Surpierre', 'Fribourg'),
                ('Vallon', 'Fribourg'),
                ('Les Montets', 'Fribourg'),
                ('Delley-Portalban', 'Fribourg'),
                ('Belmont-Broye', 'Fribourg'),
                ('Estavayer', 'Fribourg'),
                ('Cheyres-Châbles', 'Fribourg'),
                ('Auboranges', 'Fribourg'),
                ('Billens-Hennens', 'Fribourg'),
                ('Chapelle (Glâne)', 'Fribourg'),
                ('Le Châtelard', 'Fribourg'),
                ('Châtonnaye', 'Fribourg'),
                ('Ecublens (FR)', 'Fribourg'),
                ('Grangettes', 'Fribourg'),
                ('Massonnens', 'Fribourg'),
                ('Mézières (FR)', 'Fribourg'),
                ('Montet (Glâne)', 'Fribourg'),
                ('Romont (FR)', 'Fribourg'),
                ('Rue', 'Fribourg'),
                ('Siviriez', 'Fribourg'),
                ('Ursy', 'Fribourg'),
                ('Vuisternens-devant-Romont', 'Fribourg'),
                ('Villorsonnens', 'Fribourg'),
                ('Torny', 'Fribourg'),
                ('Villaz', 'Fribourg'),
                ('Haut-Intyamon', 'Fribourg'),
                ('Pont-en-Ogoz', 'Fribourg'),
                ('Botterens', 'Fribourg'),
                ('Broc', 'Fribourg'),
                ('Bulle', 'Fribourg'),
                ('Châtel-sur-Montsalvens', 'Fribourg'),
                ('Corbières', 'Fribourg'),
                ('Crésuz', 'Fribourg'),
                ('Echarlens', 'Fribourg'),
                ('Grandvillard', 'Fribourg'),
                ('Gruyères', 'Fribourg'),
                ('Hauteville', 'Fribourg'),
                ('Jaun', 'Fribourg'),
                ('Marsens', 'Fribourg'),
                ('Morlon', 'Fribourg'),
                ('Le Pâquier (FR)', 'Fribourg'),
                ('Pont-la-Ville', 'Fribourg'),
                ('Riaz', 'Fribourg'),
                ('La Roche', 'Fribourg'),
                ('Sâles', 'Fribourg'),
                ('Sorens', 'Fribourg'),
                ('Vaulruz', 'Fribourg'),
                ('Vuadens', 'Fribourg'),
                ('Bas-Intyamon', 'Fribourg'),
                ('Val-de-Charmey', 'Fribourg'),
                ('Autigny', 'Fribourg'),
                ('Avry', 'Fribourg'),
                ('Belfaux', 'Fribourg'),
                ('Chénens', 'Fribourg'),
                ('Corminboeuf', 'Fribourg'),
                ('Cottens (FR)', 'Fribourg'),
                ('Ferpicloz', 'Fribourg'),
                ('Fribourg', 'Fribourg'),
                ('Givisiez', 'Fribourg'),
                ('Granges-Paccot', 'Fribourg'),
                ('Grolley', 'Fribourg'),
                ('Marly', 'Fribourg'),
                ('Matran', 'Fribourg'),
                ('Neyruz (FR)', 'Fribourg'),
                ('Pierrafortscha', 'Fribourg'),
                ('Ponthaux', 'Fribourg'),
                ('Le Mouret', 'Fribourg'),
                ('Treyvaux', 'Fribourg'),
                ('Villars-sur-Glâne', 'Fribourg'),
                ('Villarsel-sur-Marly', 'Fribourg'),
                ('Hauterive (FR)', 'Fribourg'),
                ('La Brillaz', 'Fribourg'),
                ('La Sonnaz', 'Fribourg'),
                ('Gibloux', 'Fribourg'),
                ('Prez', 'Fribourg'),
                ('Bois-d''Amont', 'Fribourg'),
                ('Courgevaux', 'Fribourg'),
                ('Courtepin', 'Fribourg'),
                ('Cressier (FR)', 'Fribourg'),
                ('Fräschels', 'Fribourg'),
                ('Greng', 'Fribourg'),
                ('Gurmels', 'Fribourg'),
                ('Kerzers', 'Fribourg'),
                ('Kleinbösingen', 'Fribourg'),
                ('Meyriez', 'Fribourg'),
                ('Misery-Courtion', 'Fribourg'),
                ('Muntelier', 'Fribourg'),
                ('Murten', 'Fribourg'),
                ('Ried bei Kerzers', 'Fribourg'),
                ('Ulmiz', 'Fribourg'),
                ('Mont-Vully', 'Fribourg'),
                ('Brünisried', 'Fribourg'),
                ('Düdingen', 'Fribourg'),
                ('Giffers', 'Fribourg'),
                ('Bösingen', 'Fribourg'),
                ('Heitenried', 'Fribourg'),
                ('Plaffeien', 'Fribourg'),
                ('Plasselb', 'Fribourg'),
                ('Rechthalten', 'Fribourg'),
                ('St. Silvester', 'Fribourg'),
                ('St. Ursen', 'Fribourg'),
                ('Schmitten (FR)', 'Fribourg'),
                ('Tafers', 'Fribourg'),
                ('Tentlingen', 'Fribourg'),
                ('Ueberstorf', 'Fribourg'),
                ('Wünnewil-Flamatt', 'Fribourg'),
                ('Attalens', 'Fribourg'),
                ('Bossonnens', 'Fribourg'),
                ('Châtel-Saint-Denis', 'Fribourg'),
                ('Granges (Veveyse)', 'Fribourg'),
                ('Remaufens', 'Fribourg'),
                ('Saint-Martin (FR)', 'Fribourg'),
                ('Semsales', 'Fribourg'),
                ('Le Flon', 'Fribourg'),
                ('La Verrerie', 'Fribourg'),
                ('Egerkingen', 'Solothurn'),
                ('Härkingen', 'Solothurn'),
                ('Kestenholz', 'Solothurn'),
                ('Neuendorf', 'Solothurn'),
                ('Niederbuchsiten', 'Solothurn'),
                ('Oberbuchsiten', 'Solothurn'),
                ('Oensingen', 'Solothurn'),
                ('Wolfwil', 'Solothurn'),
                ('Aedermannsdorf', 'Solothurn'),
                ('Balsthal', 'Solothurn'),
                ('Herbetswil', 'Solothurn'),
                ('Holderbank (SO)', 'Solothurn'),
                ('Laupersdorf', 'Solothurn'),
                ('Matzendorf', 'Solothurn'),
                ('Mümliswil-Ramiswil', 'Solothurn'),
                ('Welschenrohr-Gänsbrunnen', 'Solothurn'),
                ('Biezwil', 'Solothurn'),
                ('Lüterkofen-Ichertswil', 'Solothurn'),
                ('Lüterswil-Gächliwil', 'Solothurn'),
                ('Messen', 'Solothurn'),
                ('Schnottwil', 'Solothurn'),
                ('Unterramsern', 'Solothurn'),
                ('Lüsslingen-Nennigkofen', 'Solothurn'),
                ('Buchegg', 'Solothurn'),
                ('Bättwil', 'Solothurn'),
                ('Büren (SO)', 'Solothurn'),
                ('Dornach', 'Solothurn'),
                ('Gempen', 'Solothurn'),
                ('Hochwald', 'Solothurn'),
                ('Hofstetten-Flüh', 'Solothurn'),
                ('Metzerlen-Mariastein', 'Solothurn'),
                ('Nuglar-St. Pantaleon', 'Solothurn'),
                ('Rodersdorf', 'Solothurn'),
                ('Seewen', 'Solothurn'),
                ('Witterswil', 'Solothurn'),
                ('Hauenstein-Ifenthal', 'Solothurn'),
                ('Kienberg', 'Solothurn'),
                ('Lostorf', 'Solothurn'),
                ('Niedergösgen', 'Solothurn'),
                ('Obergösgen', 'Solothurn'),
                ('Stüsslingen', 'Solothurn'),
                ('Trimbach', 'Solothurn'),
                ('Winznau', 'Solothurn'),
                ('Wisen (SO)', 'Solothurn'),
                ('Erlinsbach (SO)', 'Solothurn'),
                ('Aeschi (SO)', 'Solothurn'),
                ('Biberist', 'Solothurn'),
                ('Bolken', 'Solothurn'),
                ('Deitingen', 'Solothurn'),
                ('Derendingen', 'Solothurn'),
                ('Etziken', 'Solothurn'),
                ('Gerlafingen', 'Solothurn'),
                ('Halten', 'Solothurn'),
                ('Horriwil', 'Solothurn'),
                ('Hüniken', 'Solothurn'),
                ('Kriegstetten', 'Solothurn'),
                ('Lohn-Ammannsegg', 'Solothurn'),
                ('Luterbach', 'Solothurn'),
                ('Obergerlafingen', 'Solothurn'),
                ('Oekingen', 'Solothurn'),
                ('Recherswil', 'Solothurn'),
                ('Subingen', 'Solothurn'),
                ('Zuchwil', 'Solothurn'),
                ('Drei Höfe', 'Solothurn'),
                ('Balm bei Günsberg', 'Solothurn'),
                ('Bellach', 'Solothurn'),
                ('Bettlach', 'Solothurn'),
                ('Feldbrunnen-St. Niklaus', 'Solothurn'),
                ('Flumenthal', 'Solothurn'),
                ('Grenchen', 'Solothurn'),
                ('Günsberg', 'Solothurn'),
                ('Hubersdorf', 'Solothurn'),
                ('Kammersrohr', 'Solothurn'),
                ('Langendorf', 'Solothurn'),
                ('Lommiswil', 'Solothurn'),
                ('Oberdorf (SO)', 'Solothurn'),
                ('Riedholz', 'Solothurn'),
                ('Rüttenen', 'Solothurn'),
                ('Selzach', 'Solothurn'),
                ('Boningen', 'Solothurn'),
                ('Däniken', 'Solothurn'),
                ('Dulliken', 'Solothurn'),
                ('Eppenberg-Wöschnau', 'Solothurn'),
                ('Fulenbach', 'Solothurn'),
                ('Gretzenbach', 'Solothurn'),
                ('Gunzgen', 'Solothurn'),
                ('Hägendorf', 'Solothurn'),
                ('Kappel (SO)', 'Solothurn'),
                ('Olten', 'Solothurn'),
                ('Rickenbach (SO)', 'Solothurn'),
                ('Schönenwerd', 'Solothurn'),
                ('Starrkirch-Wil', 'Solothurn'),
                ('Walterswil (SO)', 'Solothurn'),
                ('Wangen bei Olten', 'Solothurn'),
                ('Solothurn', 'Solothurn'),
                ('Bärschwil', 'Solothurn'),
                ('Beinwil (SO)', 'Solothurn'),
                ('Breitenbach', 'Solothurn'),
                ('Büsserach', 'Solothurn'),
                ('Erschwil', 'Solothurn'),
                ('Fehren', 'Solothurn'),
                ('Grindel', 'Solothurn'),
                ('Himmelried', 'Solothurn'),
                ('Kleinlützel', 'Solothurn'),
                ('Meltingen', 'Solothurn'),
                ('Nunningen', 'Solothurn'),
                ('Zullwil', 'Solothurn'),
                ('Basel', 'Basel-Stadt'),
                ('Bettingen', 'Basel-Stadt'),
                ('Riehen', 'Basel-Stadt'),
                ('Aesch (BL)', 'Basel-Landschaft'),
                ('Allschwil', 'Basel-Landschaft'),
                ('Arlesheim', 'Basel-Landschaft'),
                ('Biel-Benken', 'Basel-Landschaft'),
                ('Binningen', 'Basel-Landschaft'),
                ('Birsfelden', 'Basel-Landschaft'),
                ('Bottmingen', 'Basel-Landschaft'),
                ('Ettingen', 'Basel-Landschaft'),
                ('Münchenstein', 'Basel-Landschaft'),
                ('Muttenz', 'Basel-Landschaft'),
                ('Oberwil (BL)', 'Basel-Landschaft'),
                ('Pfeffingen', 'Basel-Landschaft'),
                ('Reinach (BL)', 'Basel-Landschaft'),
                ('Schönenbuch', 'Basel-Landschaft'),
                ('Therwil', 'Basel-Landschaft'),
                ('Blauen', 'Basel-Landschaft'),
                ('Brislach', 'Basel-Landschaft'),
                ('Burg im Leimental', 'Basel-Landschaft'),
                ('Dittingen', 'Basel-Landschaft'),
                ('Duggingen', 'Basel-Landschaft'),
                ('Grellingen', 'Basel-Landschaft'),
                ('Laufen', 'Basel-Landschaft'),
                ('Liesberg', 'Basel-Landschaft'),
                ('Nenzlingen', 'Basel-Landschaft'),
                ('Roggenburg', 'Basel-Landschaft'),
                ('Röschenz', 'Basel-Landschaft'),
                ('Wahlen', 'Basel-Landschaft'),
                ('Zwingen', 'Basel-Landschaft'),
                ('Arisdorf', 'Basel-Landschaft'),
                ('Augst', 'Basel-Landschaft'),
                ('Bubendorf', 'Basel-Landschaft'),
                ('Frenkendorf', 'Basel-Landschaft'),
                ('Füllinsdorf', 'Basel-Landschaft'),
                ('Giebenach', 'Basel-Landschaft'),
                ('Hersberg', 'Basel-Landschaft'),
                ('Lausen', 'Basel-Landschaft'),
                ('Liestal', 'Basel-Landschaft'),
                ('Lupsingen', 'Basel-Landschaft'),
                ('Pratteln', 'Basel-Landschaft'),
                ('Ramlinsburg', 'Basel-Landschaft'),
                ('Seltisberg', 'Basel-Landschaft'),
                ('Ziefen', 'Basel-Landschaft'),
                ('Anwil', 'Basel-Landschaft'),
                ('Böckten', 'Basel-Landschaft'),
                ('Buckten', 'Basel-Landschaft'),
                ('Buus', 'Basel-Landschaft'),
                ('Diepflingen', 'Basel-Landschaft'),
                ('Gelterkinden', 'Basel-Landschaft'),
                ('Häfelfingen', 'Basel-Landschaft'),
                ('Hemmiken', 'Basel-Landschaft'),
                ('Itingen', 'Basel-Landschaft'),
                ('Känerkinden', 'Basel-Landschaft'),
                ('Kilchberg (BL)', 'Basel-Landschaft'),
                ('Läufelfingen', 'Basel-Landschaft'),
                ('Maisprach', 'Basel-Landschaft'),
                ('Nusshof', 'Basel-Landschaft'),
                ('Oltingen', 'Basel-Landschaft'),
                ('Ormalingen', 'Basel-Landschaft'),
                ('Rickenbach (BL)', 'Basel-Landschaft'),
                ('Rothenfluh', 'Basel-Landschaft'),
                ('Rümlingen', 'Basel-Landschaft'),
                ('Rünenberg', 'Basel-Landschaft'),
                ('Sissach', 'Basel-Landschaft'),
                ('Tecknau', 'Basel-Landschaft'),
                ('Tenniken', 'Basel-Landschaft'),
                ('Thürnen', 'Basel-Landschaft'),
                ('Wenslingen', 'Basel-Landschaft'),
                ('Wintersingen', 'Basel-Landschaft'),
                ('Wittinsburg', 'Basel-Landschaft'),
                ('Zeglingen', 'Basel-Landschaft'),
                ('Zunzgen', 'Basel-Landschaft'),
                ('Arboldswil', 'Basel-Landschaft'),
                ('Bennwil', 'Basel-Landschaft'),
                ('Bretzwil', 'Basel-Landschaft'),
                ('Diegten', 'Basel-Landschaft'),
                ('Eptingen', 'Basel-Landschaft'),
                ('Hölstein', 'Basel-Landschaft'),
                ('Lampenberg', 'Basel-Landschaft'),
                ('Langenbruck', 'Basel-Landschaft'),
                ('Lauwil', 'Basel-Landschaft'),
                ('Liedertswil', 'Basel-Landschaft'),
                ('Niederdorf', 'Basel-Landschaft'),
                ('Oberdorf (BL)', 'Basel-Landschaft'),
                ('Reigoldswil', 'Basel-Landschaft'),
                ('Titterten', 'Basel-Landschaft'),
                ('Waldenburg', 'Basel-Landschaft'),
                ('Gächlingen', 'Schaffhausen'),
                ('Löhningen', 'Schaffhausen'),
                ('Neunkirch', 'Schaffhausen'),
                ('Büttenhardt', 'Schaffhausen'),
                ('Dörflingen', 'Schaffhausen'),
                ('Lohn (SH)', 'Schaffhausen'),
                ('Stetten (SH)', 'Schaffhausen'),
                ('Thayngen', 'Schaffhausen'),
                ('Bargen (SH)', 'Schaffhausen'),
                ('Beringen', 'Schaffhausen'),
                ('Buchberg', 'Schaffhausen'),
                ('Merishausen', 'Schaffhausen'),
                ('Neuhausen am Rheinfall', 'Schaffhausen'),
                ('Rüdlingen', 'Schaffhausen'),
                ('Schaffhausen', 'Schaffhausen'),
                ('Beggingen', 'Schaffhausen'),
                ('Schleitheim', 'Schaffhausen'),
                ('Siblingen', 'Schaffhausen'),
                ('Buch (SH)', 'Schaffhausen'),
                ('Hemishofen', 'Schaffhausen'),
                ('Ramsen', 'Schaffhausen'),
                ('Stein am Rhein', 'Schaffhausen'),
                ('Hallau', 'Schaffhausen'),
                ('Oberhallau', 'Schaffhausen'),
                ('Trasadingen', 'Schaffhausen'),
                ('Wilchingen', 'Schaffhausen'),
                ('Herisau', 'Appenzell Ausserrhoden'),
                ('Hundwil', 'Appenzell Ausserrhoden'),
                ('Schönengrund', 'Appenzell Ausserrhoden'),
                ('Schwellbrunn', 'Appenzell Ausserrhoden'),
                ('Stein (AR)', 'Appenzell Ausserrhoden'),
                ('Urnäsch', 'Appenzell Ausserrhoden'),
                ('Waldstatt', 'Appenzell Ausserrhoden'),
                ('Bühler', 'Appenzell Ausserrhoden'),
                ('Gais', 'Appenzell Ausserrhoden'),
                ('Speicher', 'Appenzell Ausserrhoden'),
                ('Teufen (AR)', 'Appenzell Ausserrhoden'),
                ('Trogen', 'Appenzell Ausserrhoden'),
                ('Grub (AR)', 'Appenzell Ausserrhoden'),
                ('Heiden', 'Appenzell Ausserrhoden'),
                ('Lutzenberg', 'Appenzell Ausserrhoden'),
                ('Rehetobel', 'Appenzell Ausserrhoden'),
                ('Reute (AR)', 'Appenzell Ausserrhoden'),
                ('Wald (AR)', 'Appenzell Ausserrhoden'),
                ('Walzenhausen', 'Appenzell Ausserrhoden'),
                ('Wolfhalden', 'Appenzell Ausserrhoden'),
                ('Appenzell', 'Appenzell Innerrhoden'),
                ('Gonten', 'Appenzell Innerrhoden'),
                ('Rüte', 'Appenzell Innerrhoden'),
                ('Schlatt-Haslen', 'Appenzell Innerrhoden'),
                ('Schwende', 'Appenzell Innerrhoden'),
                ('Oberegg', 'Appenzell Innerrhoden'),
                ('Häggenschwil', 'St. Gallen'),
                ('Muolen', 'St. Gallen'),
                ('St. Gallen', 'St. Gallen'),
                ('Wittenbach', 'St. Gallen'),
                ('Berg (SG)', 'St. Gallen'),
                ('Eggersriet', 'St. Gallen'),
                ('Goldach', 'St. Gallen'),
                ('Mörschwil', 'St. Gallen'),
                ('Rorschach', 'St. Gallen'),
                ('Rorschacherberg', 'St. Gallen'),
                ('Steinach', 'St. Gallen'),
                ('Tübach', 'St. Gallen'),
                ('Untereggen', 'St. Gallen'),
                ('Au (SG)', 'St. Gallen'),
                ('Balgach', 'St. Gallen'),
                ('Berneck', 'St. Gallen'),
                ('Diepoldsau', 'St. Gallen'),
                ('Rheineck', 'St. Gallen'),
                ('St. Margrethen', 'St. Gallen'),
                ('Thal', 'St. Gallen'),
                ('Widnau', 'St. Gallen'),
                ('Altstätten', 'St. Gallen'),
                ('Eichberg', 'St. Gallen'),
                ('Marbach (SG)', 'St. Gallen'),
                ('Oberriet (SG)', 'St. Gallen'),
                ('Rebstein', 'St. Gallen'),
                ('Rüthi (SG)', 'St. Gallen'),
                ('Buchs (SG)', 'St. Gallen'),
                ('Gams', 'St. Gallen'),
                ('Grabs', 'St. Gallen'),
                ('Sennwald', 'St. Gallen'),
                ('Sevelen', 'St. Gallen'),
                ('Wartau', 'St. Gallen'),
                ('Bad Ragaz', 'St. Gallen'),
                ('Flums', 'St. Gallen'),
                ('Mels', 'St. Gallen'),
                ('Pfäfers', 'St. Gallen'),
                ('Quarten', 'St. Gallen'),
                ('Sargans', 'St. Gallen'),
                ('Vilters-Wangs', 'St. Gallen'),
                ('Walenstadt', 'St. Gallen'),
                ('Amden', 'St. Gallen'),
                ('Benken (SG)', 'St. Gallen'),
                ('Kaltbrunn', 'St. Gallen'),
                ('Schänis', 'St. Gallen'),
                ('Weesen', 'St. Gallen'),
                ('Schmerikon', 'St. Gallen'),
                ('Uznach', 'St. Gallen'),
                ('Rapperswil-Jona', 'St. Gallen'),
                ('Gommiswald', 'St. Gallen'),
                ('Eschenbach (SG)', 'St. Gallen'),
                ('Ebnat-Kappel', 'St. Gallen'),
                ('Wildhaus-Alt St. Johann', 'St. Gallen'),
                ('Nesslau', 'St. Gallen'),
                ('Hemberg', 'St. Gallen'),
                ('Lichtensteig', 'St. Gallen'),
                ('Oberhelfenschwil', 'St. Gallen'),
                ('Neckertal', 'St. Gallen'),
                ('Wattwil', 'St. Gallen'),
                ('Kirchberg (SG)', 'St. Gallen'),
                ('Lütisburg', 'St. Gallen'),
                ('Mosnang', 'St. Gallen'),
                ('Bütschwil-Ganterschwil', 'St. Gallen'),
                ('Degersheim', 'St. Gallen'),
                ('Flawil', 'St. Gallen'),
                ('Jonschwil', 'St. Gallen'),
                ('Oberuzwil', 'St. Gallen'),
                ('Uzwil', 'St. Gallen'),
                ('Niederbüren', 'St. Gallen'),
                ('Niederhelfenschwil', 'St. Gallen'),
                ('Oberbüren', 'St. Gallen'),
                ('Zuzwil (SG)', 'St. Gallen'),
                ('Wil (SG)', 'St. Gallen'),
                ('Andwil (SG)', 'St. Gallen'),
                ('Gaiserwald', 'St. Gallen'),
                ('Gossau (SG)', 'St. Gallen'),
                ('Waldkirch', 'St. Gallen'),
                ('Vaz/Obervaz', 'Graubünden'),
                ('Lantsch/Lenz', 'Graubünden'),
                ('Schmitten (GR)', 'Graubünden'),
                ('Albula/Alvra', 'Graubünden'),
                ('Surses', 'Graubünden'),
                ('Bergün Filisur', 'Graubünden'),
                ('Brusio', 'Graubünden'),
                ('Poschiavo', 'Graubünden'),
                ('Falera', 'Graubünden'),
                ('Laax', 'Graubünden'),
                ('Sagogn', 'Graubünden'),
                ('Schluein', 'Graubünden'),
                ('Vals', 'Graubünden'),
                ('Lumnezia', 'Graubünden'),
                ('Ilanz/Glion', 'Graubünden'),
                ('Fürstenau', 'Graubünden'),
                ('Rothenbrunnen', 'Graubünden'),
                ('Scharans', 'Graubünden'),
                ('Sils im Domleschg', 'Graubünden'),
                ('Cazis', 'Graubünden'),
                ('Flerden', 'Graubünden'),
                ('Masein', 'Graubünden'),
                ('Thusis', 'Graubünden'),
                ('Tschappina', 'Graubünden'),
                ('Urmein', 'Graubünden'),
                ('Safiental', 'Graubünden'),
                ('Domleschg', 'Graubünden'),
                ('Avers', 'Graubünden'),
                ('Sufers', 'Graubünden'),
                ('Andeer', 'Graubünden'),
                ('Rongellen', 'Graubünden'),
                ('Zillis-Reischen', 'Graubünden'),
                ('Ferrera', 'Graubünden'),
                ('Rheinwald', 'Graubünden'),
                ('Muntogna da Schons', 'Graubünden'),
                ('Bonaduz', 'Graubünden'),
                ('Domat/Ems', 'Graubünden'),
                ('Rhäzüns', 'Graubünden'),
                ('Felsberg', 'Graubünden'),
                ('Flims', 'Graubünden'),
                ('Tamins', 'Graubünden'),
                ('Trin', 'Graubünden'),
                ('Zernez', 'Graubünden'),
                ('Samnaun', 'Graubünden'),
                ('Scuol', 'Graubünden'),
                ('Valsot', 'Graubünden'),
                ('Bever', 'Graubünden'),
                ('Celerina/Schlarigna', 'Graubünden'),
                ('Madulain', 'Graubünden'),
                ('Pontresina', 'Graubünden'),
                ('La Punt Chamues-ch', 'Graubünden'),
                ('Samedan', 'Graubünden'),
                ('St. Moritz', 'Graubünden'),
                ('S-chanf', 'Graubünden'),
                ('Sils im Engadin/Segl', 'Graubünden'),
                ('Silvaplana', 'Graubünden'),
                ('Zuoz', 'Graubünden'),
                ('Bregaglia', 'Graubünden'),
                ('Buseno', 'Graubünden'),
                ('Castaneda', 'Graubünden'),
                ('Rossa', 'Graubünden'),
                ('Santa Maria IN Calanca', 'Graubünden'),
                ('Lostallo', 'Graubünden'),
                ('Mesocco', 'Graubünden'),
                ('Soazza', 'Graubünden'),
                ('Cama', 'Graubünden'),
                ('Grono', 'Graubünden'),
                ('Roveredo (GR)', 'Graubünden'),
                ('San Vittore', 'Graubünden'),
                ('Calanca', 'Graubünden'),
                ('Val Müstair', 'Graubünden'),
                ('Davos', 'Graubünden'),
                ('Fideris', 'Graubünden'),
                ('Furna', 'Graubünden'),
                ('Jenaz', 'Graubünden'),
                ('Klosters', 'Graubünden'),
                ('Conters im Prättigau', 'Graubünden'),
                ('Küblis', 'Graubünden'),
                ('Luzein', 'Graubünden'),
                ('Chur', 'Graubünden'),
                ('Churwalden', 'Graubünden'),
                ('Arosa', 'Graubünden'),
                ('Tschiertschen-Praden', 'Graubünden'),
                ('Trimmis', 'Graubünden'),
                ('Untervaz', 'Graubünden'),
                ('Zizers', 'Graubünden'),
                ('Fläsch', 'Graubünden'),
                ('Jenins', 'Graubünden'),
                ('Maienfeld', 'Graubünden'),
                ('Malans', 'Graubünden'),
                ('Landquart', 'Graubünden'),
                ('Grüsch', 'Graubünden'),
                ('Schiers', 'Graubünden'),
                ('Seewis im Prättigau', 'Graubünden'),
                ('Breil/Brigels', 'Graubünden'),
                ('Disentis/Mustér', 'Graubünden'),
                ('Medel (Lucmagn)', 'Graubünden'),
                ('Sumvitg', 'Graubünden'),
                ('Tujetsch', 'Graubünden'),
                ('Trun', 'Graubünden'),
                ('Obersaxen Mundaun', 'Graubünden'),
                ('Aarau', 'Aargau'),
                ('Biberstein', 'Aargau'),
                ('Buchs (AG)', 'Aargau'),
                ('Densbüren', 'Aargau'),
                ('Erlinsbach (AG)', 'Aargau'),
                ('Gränichen', 'Aargau'),
                ('Hirschthal', 'Aargau'),
                ('Küttigen', 'Aargau'),
                ('Muhen', 'Aargau'),
                ('Oberentfelden', 'Aargau'),
                ('Suhr', 'Aargau'),
                ('Unterentfelden', 'Aargau'),
                ('Baden', 'Aargau'),
                ('Bellikon', 'Aargau'),
                ('Bergdietikon', 'Aargau'),
                ('Birmenstorf (AG)', 'Aargau'),
                ('Ennetbaden', 'Aargau'),
                ('Fislisbach', 'Aargau'),
                ('Freienwil', 'Aargau'),
                ('Gebenstorf', 'Aargau'),
                ('Killwangen', 'Aargau'),
                ('Künten', 'Aargau'),
                ('Mägenwil', 'Aargau'),
                ('Mellingen', 'Aargau'),
                ('Neuenhof', 'Aargau'),
                ('Niederrohrdorf', 'Aargau'),
                ('Oberrohrdorf', 'Aargau'),
                ('Obersiggenthal', 'Aargau'),
                ('Remetschwil', 'Aargau'),
                ('Spreitenbach', 'Aargau'),
                ('Stetten (AG)', 'Aargau'),
                ('Turgi', 'Aargau'),
                ('Untersiggenthal', 'Aargau'),
                ('Wettingen', 'Aargau'),
                ('Wohlenschwil', 'Aargau'),
                ('Würenlingen', 'Aargau'),
                ('Würenlos', 'Aargau'),
                ('Ehrendingen', 'Aargau'),
                ('Arni (AG)', 'Aargau'),
                ('Berikon', 'Aargau'),
                ('Bremgarten (AG)', 'Aargau'),
                ('Büttikon', 'Aargau'),
                ('Dottikon', 'Aargau'),
                ('Eggenwil', 'Aargau'),
                ('Fischbach-Göslikon', 'Aargau'),
                ('Hägglingen', 'Aargau'),
                ('Jonen', 'Aargau'),
                ('Niederwil (AG)', 'Aargau'),
                ('Oberlunkhofen', 'Aargau'),
                ('Oberwil-Lieli', 'Aargau'),
                ('Rudolfstetten-Friedlisberg', 'Aargau'),
                ('Sarmenstorf', 'Aargau'),
                ('Tägerig', 'Aargau'),
                ('Uezwil', 'Aargau'),
                ('Unterlunkhofen', 'Aargau'),
                ('Villmergen', 'Aargau'),
                ('Widen', 'Aargau'),
                ('Wohlen (AG)', 'Aargau'),
                ('Zufikon', 'Aargau'),
                ('Islisberg', 'Aargau'),
                ('Auenstein', 'Aargau'),
                ('Birr', 'Aargau'),
                ('Birrhard', 'Aargau'),
                ('Brugg', 'Aargau'),
                ('Habsburg', 'Aargau'),
                ('Hausen (AG)', 'Aargau'),
                ('Lupfig', 'Aargau'),
                ('Mandach', 'Aargau'),
                ('Mönthal', 'Aargau'),
                ('Mülligen', 'Aargau'),
                ('Remigen', 'Aargau'),
                ('Riniken', 'Aargau'),
                ('Rüfenach', 'Aargau'),
                ('Thalheim (AG)', 'Aargau'),
                ('Veltheim (AG)', 'Aargau'),
                ('Villigen', 'Aargau'),
                ('Villnachern', 'Aargau'),
                ('Windisch', 'Aargau'),
                ('Bözberg', 'Aargau'),
                ('Schinznach', 'Aargau'),
                ('Beinwil am See', 'Aargau'),
                ('Birrwil', 'Aargau'),
                ('Burg (AG)', 'Aargau'),
                ('Dürrenäsch', 'Aargau'),
                ('Gontenschwil', 'Aargau'),
                ('Holziken', 'Aargau'),
                ('Leimbach (AG)', 'Aargau'),
                ('Leutwil', 'Aargau'),
                ('Menziken', 'Aargau'),
                ('Oberkulm', 'Aargau'),
                ('Reinach (AG)', 'Aargau'),
                ('Schlossrued', 'Aargau'),
                ('Schmiedrued', 'Aargau'),
                ('Schöftland', 'Aargau'),
                ('Teufenthal (AG)', 'Aargau'),
                ('Unterkulm', 'Aargau'),
                ('Zetzwil', 'Aargau'),
                ('Eiken', 'Aargau'),
                ('Frick', 'Aargau'),
                ('Gansingen', 'Aargau'),
                ('Gipf-Oberfrick', 'Aargau'),
                ('Herznach', 'Aargau'),
                ('Kaisten', 'Aargau'),
                ('Laufenburg', 'Aargau'),
                ('Münchwilen (AG)', 'Aargau'),
                ('Oberhof', 'Aargau'),
                ('Oeschgen', 'Aargau'),
                ('Schwaderloch', 'Aargau'),
                ('Sisseln', 'Aargau'),
                ('Ueken', 'Aargau'),
                ('Wittnau', 'Aargau'),
                ('Wölflinswil', 'Aargau'),
                ('Zeihen', 'Aargau'),
                ('Mettauertal', 'Aargau'),
                ('Böztal', 'Aargau'),
                ('Ammerswil', 'Aargau'),
                ('Boniswil', 'Aargau'),
                ('Brunegg', 'Aargau'),
                ('Dintikon', 'Aargau'),
                ('Egliswil', 'Aargau'),
                ('Fahrwangen', 'Aargau'),
                ('Hallwil', 'Aargau'),
                ('Hendschiken', 'Aargau'),
                ('Holderbank (AG)', 'Aargau'),
                ('Hunzenschwil', 'Aargau'),
                ('Lenzburg', 'Aargau'),
                ('Meisterschwanden', 'Aargau'),
                ('Möriken-Wildegg', 'Aargau'),
                ('Niederlenz', 'Aargau'),
                ('Othmarsingen', 'Aargau'),
                ('Rupperswil', 'Aargau'),
                ('Schafisheim', 'Aargau'),
                ('Seengen', 'Aargau'),
                ('Seon', 'Aargau'),
                ('Staufen', 'Aargau'),
                ('Abtwil', 'Aargau'),
                ('Aristau', 'Aargau'),
                ('Auw', 'Aargau'),
                ('Beinwil (Freiamt)', 'Aargau'),
                ('Besenbüren', 'Aargau'),
                ('Bettwil', 'Aargau'),
                ('Boswil', 'Aargau'),
                ('Bünzen', 'Aargau'),
                ('Buttwil', 'Aargau'),
                ('Dietwil', 'Aargau'),
                ('Geltwil', 'Aargau'),
                ('Kallern', 'Aargau'),
                ('Merenschwand', 'Aargau'),
                ('Mühlau', 'Aargau'),
                ('Muri (AG)', 'Aargau'),
                ('Oberrüti', 'Aargau'),
                ('Rottenschwil', 'Aargau'),
                ('Sins', 'Aargau'),
                ('Waltenschwil', 'Aargau'),
                ('Hellikon', 'Aargau'),
                ('Kaiseraugst', 'Aargau'),
                ('Magden', 'Aargau'),
                ('Möhlin', 'Aargau'),
                ('Mumpf', 'Aargau'),
                ('Obermumpf', 'Aargau'),
                ('Olsberg', 'Aargau'),
                ('Rheinfelden', 'Aargau'),
                ('Schupfart', 'Aargau'),
                ('Stein (AG)', 'Aargau'),
                ('Wallbach', 'Aargau'),
                ('Wegenstetten', 'Aargau'),
                ('Zeiningen', 'Aargau'),
                ('Zuzgen', 'Aargau'),
                ('Aarburg', 'Aargau'),
                ('Bottenwil', 'Aargau'),
                ('Brittnau', 'Aargau'),
                ('Kirchleerau', 'Aargau'),
                ('Kölliken', 'Aargau'),
                ('Moosleerau', 'Aargau'),
                ('Murgenthal', 'Aargau'),
                ('Oftringen', 'Aargau'),
                ('Reitnau', 'Aargau'),
                ('Rothrist', 'Aargau'),
                ('Safenwil', 'Aargau'),
                ('Staffelbach', 'Aargau'),
                ('Strengelbach', 'Aargau'),
                ('Uerkheim', 'Aargau'),
                ('Vordemwald', 'Aargau'),
                ('Wiliberg', 'Aargau'),
                ('Zofingen', 'Aargau'),
                ('Böttstein', 'Aargau'),
                ('Döttingen', 'Aargau'),
                ('Endingen', 'Aargau'),
                ('Fisibach', 'Aargau'),
                ('FULL-Reuenthal', 'Aargau'),
                ('Klingnau', 'Aargau'),
                ('Koblenz', 'Aargau'),
                ('Leibstadt', 'Aargau'),
                ('Lengnau (AG)', 'Aargau'),
                ('Leuggern', 'Aargau'),
                ('Mellikon', 'Aargau'),
                ('Schneisingen', 'Aargau'),
                ('Siglistorf', 'Aargau'),
                ('Tegerfelden', 'Aargau'),
                ('Zurzach', 'Aargau'),
                ('Arbon', 'Thurgau'),
                ('Dozwil', 'Thurgau'),
                ('Egnach', 'Thurgau'),
                ('Hefenhofen', 'Thurgau'),
                ('Horn', 'Thurgau'),
                ('Kesswil', 'Thurgau'),
                ('Roggwil (TG)', 'Thurgau'),
                ('Romanshorn', 'Thurgau'),
                ('Salmsach', 'Thurgau'),
                ('Sommeri', 'Thurgau'),
                ('Uttwil', 'Thurgau'),
                ('Amriswil', 'Thurgau'),
                ('Bischofszell', 'Thurgau'),
                ('Erlen', 'Thurgau'),
                ('Hauptwil-Gottshaus', 'Thurgau'),
                ('Hohentannen', 'Thurgau'),
                ('Kradolf-Schönenberg', 'Thurgau'),
                ('Sulgen', 'Thurgau'),
                ('Zihlschlacht-Sitterdorf', 'Thurgau'),
                ('Basadingen-Schlattingen', 'Thurgau'),
                ('Diessenhofen', 'Thurgau'),
                ('Schlatt (TG)', 'Thurgau'),
                ('Aadorf', 'Thurgau'),
                ('Felben-Wellhausen', 'Thurgau'),
                ('Frauenfeld', 'Thurgau'),
                ('Gachnang', 'Thurgau'),
                ('Hüttlingen', 'Thurgau'),
                ('Matzingen', 'Thurgau'),
                ('Neunforn', 'Thurgau'),
                ('Stettfurt', 'Thurgau'),
                ('Thundorf', 'Thurgau'),
                ('Uesslingen-Buch', 'Thurgau'),
                ('Warth-Weiningen', 'Thurgau'),
                ('Altnau', 'Thurgau'),
                ('Bottighofen', 'Thurgau'),
                ('Ermatingen', 'Thurgau'),
                ('Gottlieben', 'Thurgau'),
                ('Güttingen', 'Thurgau'),
                ('Kemmental', 'Thurgau'),
                ('Kreuzlingen', 'Thurgau'),
                ('Langrickenbach', 'Thurgau'),
                ('Lengwil', 'Thurgau'),
                ('Münsterlingen', 'Thurgau'),
                ('Tägerwilen', 'Thurgau'),
                ('Wäldi', 'Thurgau'),
                ('Affeltrangen', 'Thurgau'),
                ('Bettwiesen', 'Thurgau'),
                ('Bichelsee-Balterswil', 'Thurgau'),
                ('Braunau', 'Thurgau'),
                ('Eschlikon', 'Thurgau'),
                ('Fischingen', 'Thurgau'),
                ('Lommis', 'Thurgau'),
                ('Münchwilen (TG)', 'Thurgau'),
                ('Rickenbach (TG)', 'Thurgau'),
                ('Schönholzerswilen', 'Thurgau'),
                ('Sirnach', 'Thurgau'),
                ('Tobel-Tägerschen', 'Thurgau'),
                ('Wängi', 'Thurgau'),
                ('Wilen (TG)', 'Thurgau'),
                ('Wuppenau', 'Thurgau'),
                ('Berlingen', 'Thurgau'),
                ('Eschenz', 'Thurgau'),
                ('Herdern', 'Thurgau'),
                ('Homburg', 'Thurgau'),
                ('Hüttwilen', 'Thurgau'),
                ('Mammern', 'Thurgau'),
                ('Müllheim', 'Thurgau'),
                ('Pfyn', 'Thurgau'),
                ('Raperswilen', 'Thurgau'),
                ('Salenstein', 'Thurgau'),
                ('Steckborn', 'Thurgau'),
                ('Wagenhausen', 'Thurgau'),
                ('Amlikon-Bissegg', 'Thurgau'),
                ('Berg (TG)', 'Thurgau'),
                ('Birwinken', 'Thurgau'),
                ('Bürglen (TG)', 'Thurgau'),
                ('Bussnang', 'Thurgau'),
                ('Märstetten', 'Thurgau'),
                ('Weinfelden', 'Thurgau'),
                ('Wigoltingen', 'Thurgau'),
                ('Arbedo-Castione', 'Ticino'),
                ('Bellinzona', 'Ticino'),
                ('Cadenazzo', 'Ticino'),
                ('Isone', 'Ticino'),
                ('Lumino', 'Ticino'),
                ('Sant''Antonino', 'Ticino'),
                ('Acquarossa', 'Ticino'),
                ('Blenio', 'Ticino'),
                ('Serravalle', 'Ticino'),
                ('Airolo', 'Ticino'),
                ('Bedretto', 'Ticino'),
                ('Bodio', 'Ticino'),
                ('Dalpe', 'Ticino'),
                ('Faido', 'Ticino'),
                ('Giornico', 'Ticino'),
                ('Personico', 'Ticino'),
                ('Pollegio', 'Ticino'),
                ('Prato (Leventina)', 'Ticino'),
                ('Quinto', 'Ticino'),
                ('Ascona', 'Ticino'),
                ('Brione sopra Minusio', 'Ticino'),
                ('Brissago', 'Ticino'),
                ('Gordola', 'Ticino'),
                ('Lavertezzo', 'Ticino'),
                ('Locarno', 'Ticino'),
                ('Losone', 'Ticino'),
                ('Mergoscia', 'Ticino'),
                ('Minusio', 'Ticino'),
                ('Muralto', 'Ticino'),
                ('Orselina', 'Ticino'),
                ('Ronco sopra Ascona', 'Ticino'),
                ('Tenero-Contra', 'Ticino'),
                ('Onsernone', 'Ticino'),
                ('Cugnasco-Gerra', 'Ticino'),
                ('Agno', 'Ticino'),
                ('Aranno', 'Ticino'),
                ('Arogno', 'Ticino'),
                ('Astano', 'Ticino'),
                ('Bedano', 'Ticino'),
                ('Bedigliora', 'Ticino'),
                ('Bioggio', 'Ticino'),
                ('Bissone', 'Ticino'),
                ('Brusino Arsizio', 'Ticino'),
                ('Cademario', 'Ticino'),
                ('Cadempino', 'Ticino'),
                ('Canobbio', 'Ticino'),
                ('Caslano', 'Ticino'),
                ('Comano', 'Ticino'),
                ('Cureglia', 'Ticino'),
                ('Curio', 'Ticino'),
                ('Grancia', 'Ticino'),
                ('Gravesano', 'Ticino'),
                ('Lamone', 'Ticino'),
                ('Lugano', 'Ticino'),
                ('Magliaso', 'Ticino'),
                ('Manno', 'Ticino'),
                ('Maroggia', 'Ticino'),
                ('Massagno', 'Ticino'),
                ('Melano', 'Ticino'),
                ('Melide', 'Ticino'),
                ('Mezzovico-Vira', 'Ticino'),
                ('Miglieglia', 'Ticino'),
                ('Morcote', 'Ticino'),
                ('Muzzano', 'Ticino'),
                ('Neggio', 'Ticino'),
                ('Novaggio', 'Ticino'),
                ('Origlio', 'Ticino'),
                ('Paradiso', 'Ticino'),
                ('Ponte Capriasca', 'Ticino'),
                ('Porza', 'Ticino'),
                ('Pura', 'Ticino'),
                ('Rovio', 'Ticino'),
                ('Savosa', 'Ticino'),
                ('Sorengo', 'Ticino'),
                ('Capriasca', 'Ticino'),
                ('Torricella-Taverne', 'Ticino'),
                ('Vernate', 'Ticino'),
                ('Vezia', 'Ticino'),
                ('Vico Morcote', 'Ticino'),
                ('Collina D''Oro', 'Ticino'),
                ('Alto Malcantone', 'Ticino'),
                ('Monteceneri', 'Ticino'),
                ('Tresa', 'Ticino'),
                ('Balerna', 'Ticino'),
                ('Castel San Pietro', 'Ticino'),
                ('Chiasso', 'Ticino'),
                ('Coldrerio', 'Ticino'),
                ('Mendrisio', 'Ticino'),
                ('Morbio Inferiore', 'Ticino'),
                ('Novazzano', 'Ticino'),
                ('Riva San Vitale', 'Ticino'),
                ('Stabio', 'Ticino'),
                ('Vacallo', 'Ticino'),
                ('Breggia', 'Ticino'),
                ('Biasca', 'Ticino'),
                ('Riviera', 'Ticino'),
                ('Bosco/Gurin', 'Ticino'),
                ('Campo (Vallemaggia)', 'Ticino'),
                ('Cerentino', 'Ticino'),
                ('Cevio', 'Ticino'),
                ('Linescio', 'Ticino'),
                ('Maggia', 'Ticino'),
                ('Lavizzara', 'Ticino'),
                ('Avegno Gordevio', 'Ticino'),
                ('Terre di Pedemonte', 'Ticino'),
                ('Centovalli', 'Ticino'),
                ('Gambarogno', 'Ticino'),
                ('Verzasca', 'Ticino'),
                ('Aigle', 'Vaud'),
                ('Bex', 'Vaud'),
                ('Chessel', 'Vaud'),
                ('Corbeyrier', 'Vaud'),
                ('Gryon', 'Vaud'),
                ('Lavey-Morcles', 'Vaud'),
                ('Leysin', 'Vaud'),
                ('Noville', 'Vaud'),
                ('Ollon', 'Vaud'),
                ('Ormont-Dessous', 'Vaud'),
                ('Ormont-Dessus', 'Vaud'),
                ('Rennaz', 'Vaud'),
                ('Roche (VD)', 'Vaud'),
                ('Villeneuve (VD)', 'Vaud'),
                ('Yvorne', 'Vaud'),
                ('Aubonne', 'Vaud'),
                ('Ballens', 'Vaud'),
                ('Berolle', 'Vaud'),
                ('Bière', 'Vaud'),
                ('Bougy-Villars', 'Vaud'),
                ('Féchy', 'Vaud'),
                ('Gimel', 'Vaud'),
                ('Longirod', 'Vaud'),
                ('Marchissy', 'Vaud'),
                ('Mollens (VD)', 'Vaud'),
                ('Saint-George', 'Vaud'),
                ('Saint-Livres', 'Vaud'),
                ('Saint-Oyens', 'Vaud'),
                ('Saubraz', 'Vaud'),
                ('Avenches', 'Vaud'),
                ('Cudrefin', 'Vaud'),
                ('Faoug', 'Vaud'),
                ('Vully-les-Lacs', 'Vaud'),
                ('Bettens', 'Vaud'),
                ('Bournens', 'Vaud'),
                ('Boussens', 'Vaud'),
                ('La Chaux (Cossonay)', 'Vaud'),
                ('Chavannes-le-Veyron', 'Vaud'),
                ('Chevilly', 'Vaud'),
                ('Cossonay', 'Vaud'),
                ('Cuarnens', 'Vaud'),
                ('Daillens', 'Vaud'),
                ('Dizy', 'Vaud'),
                ('Eclépens', 'Vaud'),
                ('Ferreyres', 'Vaud'),
                ('Gollion', 'Vaud'),
                ('Grancy', 'Vaud'),
                ('L''Isle', 'Vaud'),
                ('Lussery-Villars', 'Vaud'),
                ('Mauraz', 'Vaud'),
                ('Mex (VD)', 'Vaud'),
                ('Moiry', 'Vaud'),
                ('Mont-la-Ville', 'Vaud'),
                ('Montricher', 'Vaud'),
                ('Orny', 'Vaud'),
                ('Penthalaz', 'Vaud'),
                ('Penthaz', 'Vaud'),
                ('Pompaples', 'Vaud'),
                ('La Sarraz', 'Vaud'),
                ('Senarclens', 'Vaud'),
                ('Sullens', 'Vaud'),
                ('Vufflens-la-Ville', 'Vaud'),
                ('Assens', 'Vaud'),
                ('Bercher', 'Vaud'),
                ('Bottens', 'Vaud'),
                ('Bretigny-sur-Morrens', 'Vaud'),
                ('Cugy (VD)', 'Vaud'),
                ('Echallens', 'Vaud'),
                ('Essertines-sur-Yverdon', 'Vaud'),
                ('Etagnières', 'Vaud'),
                ('Fey', 'Vaud'),
                ('Froideville', 'Vaud'),
                ('Morrens (VD)', 'Vaud'),
                ('Oulens-sous-Echallens', 'Vaud'),
                ('Pailly', 'Vaud'),
                ('Penthéréaz', 'Vaud'),
                ('Poliez-Pittet', 'Vaud'),
                ('Rueyres', 'Vaud'),
                ('Saint-Barthélemy (VD)', 'Vaud'),
                ('Villars-le-Terroir', 'Vaud'),
                ('Vuarrens', 'Vaud'),
                ('Montilliez', 'Vaud'),
                ('Goumoëns', 'Vaud'),
                ('Bonvillars', 'Vaud'),
                ('Bullet', 'Vaud'),
                ('Champagne', 'Vaud'),
                ('Concise', 'Vaud'),
                ('Corcelles-près-Concise', 'Vaud'),
                ('Fiez', 'Vaud'),
                ('Fontaines-sur-Grandson', 'Vaud'),
                ('Giez', 'Vaud'),
                ('Grandevent', 'Vaud'),
                ('Grandson', 'Vaud'),
                ('Mauborget', 'Vaud'),
                ('Mutrux', 'Vaud'),
                ('Novalles', 'Vaud'),
                ('Onnens (VD)', 'Vaud'),
                ('Provence', 'Vaud'),
                ('Sainte-Croix', 'Vaud'),
                ('Tévenon', 'Vaud'),
                ('Belmont-sur-Lausanne', 'Vaud'),
                ('Cheseaux-sur-Lausanne', 'Vaud'),
                ('Crissier', 'Vaud'),
                ('Epalinges', 'Vaud'),
                ('Jouxtens-Mézery', 'Vaud'),
                ('Lausanne', 'Vaud'),
                ('Le Mont-sur-Lausanne', 'Vaud'),
                ('Paudex', 'Vaud'),
                ('Prilly', 'Vaud'),
                ('Pully', 'Vaud'),
                ('Renens (VD)', 'Vaud'),
                ('Romanel-sur-Lausanne', 'Vaud'),
                ('Chexbres', 'Vaud'),
                ('Forel (Lavaux)', 'Vaud'),
                ('Lutry', 'Vaud'),
                ('Puidoux', 'Vaud'),
                ('Rivaz', 'Vaud'),
                ('Saint-Saphorin (Lavaux)', 'Vaud'),
                ('Savigny', 'Vaud'),
                ('Bourg-en-Lavaux', 'Vaud'),
                ('Aclens', 'Vaud'),
                ('Bremblens', 'Vaud'),
                ('Buchillon', 'Vaud'),
                ('Bussigny', 'Vaud'),
                ('Chavannes-près-Renens', 'Vaud'),
                ('Chigny', 'Vaud'),
                ('Clarmont', 'Vaud'),
                ('Denens', 'Vaud'),
                ('Denges', 'Vaud'),
                ('Echandens', 'Vaud'),
                ('Echichens', 'Vaud'),
                ('Ecublens (VD)', 'Vaud'),
                ('Etoy', 'Vaud'),
                ('Lavigny', 'Vaud'),
                ('Lonay', 'Vaud'),
                ('Lully (VD)', 'Vaud'),
                ('Lussy-sur-Morges', 'Vaud'),
                ('Morges', 'Vaud'),
                ('Préverenges', 'Vaud'),
                ('Romanel-sur-Morges', 'Vaud'),
                ('Saint-Prex', 'Vaud'),
                ('Saint-Sulpice (VD)', 'Vaud'),
                ('Tolochenaz', 'Vaud'),
                ('Vaux-sur-Morges', 'Vaud'),
                ('Villars-Sainte-Croix', 'Vaud'),
                ('Villars-sous-Yens', 'Vaud'),
                ('Vufflens-le-Château', 'Vaud'),
                ('Vullierens', 'Vaud'),
                ('Yens', 'Vaud'),
                ('Hautemorges', 'Vaud'),
                ('Boulens', 'Vaud'),
                ('Bussy-sur-Moudon', 'Vaud'),
                ('Chavannes-sur-Moudon', 'Vaud'),
                ('Curtilles', 'Vaud'),
                ('Dompierre (VD)', 'Vaud'),
                ('Hermenches', 'Vaud'),
                ('Lovatens', 'Vaud'),
                ('Lucens', 'Vaud'),
                ('Moudon', 'Vaud'),
                ('Ogens', 'Vaud'),
                ('Prévonloup', 'Vaud'),
                ('Rossenges', 'Vaud'),
                ('Syens', 'Vaud'),
                ('Villars-le-Comte', 'Vaud'),
                ('Vucherens', 'Vaud'),
                ('Montanaire', 'Vaud'),
                ('Arnex-sur-Nyon', 'Vaud'),
                ('Arzier-Le Muids', 'Vaud'),
                ('Bassins', 'Vaud'),
                ('Begnins', 'Vaud'),
                ('Bogis-Bossey', 'Vaud'),
                ('Borex', 'Vaud'),
                ('Chavannes-de-Bogis', 'Vaud'),
                ('Chavannes-des-Bois', 'Vaud'),
                ('Chéserex', 'Vaud'),
                ('Coinsins', 'Vaud'),
                ('Commugny', 'Vaud'),
                ('Coppet', 'Vaud'),
                ('Crans (VD)', 'Vaud'),
                ('Crassier', 'Vaud'),
                ('Duillier', 'Vaud'),
                ('Eysins', 'Vaud'),
                ('Founex', 'Vaud'),
                ('Genolier', 'Vaud'),
                ('Gingins', 'Vaud'),
                ('Givrins', 'Vaud'),
                ('Gland', 'Vaud'),
                ('Grens', 'Vaud'),
                ('Mies', 'Vaud'),
                ('Nyon', 'Vaud'),
                ('Prangins', 'Vaud'),
                ('La Rippe', 'Vaud'),
                ('Saint-Cergue', 'Vaud'),
                ('Signy-Avenex', 'Vaud'),
                ('Tannay', 'Vaud'),
                ('Trélex', 'Vaud'),
                ('Le Vaud', 'Vaud'),
                ('Vich', 'Vaud'),
                ('L''Abergement', 'Vaud'),
                ('Agiez', 'Vaud'),
                ('Arnex-sur-Orbe', 'Vaud'),
                ('Ballaigues', 'Vaud'),
                ('Baulmes', 'Vaud'),
                ('Bavois', 'Vaud'),
                ('Bofflens', 'Vaud'),
                ('Bretonnières', 'Vaud'),
                ('Chavornay', 'Vaud'),
                ('Les Clées', 'Vaud'),
                ('Croy', 'Vaud'),
                ('Juriens', 'Vaud'),
                ('Lignerolle', 'Vaud'),
                ('Montcherand', 'Vaud'),
                ('Orbe', 'Vaud'),
                ('La Praz', 'Vaud'),
                ('Premier', 'Vaud'),
                ('Rances', 'Vaud'),
                ('Romainmôtier-Envy', 'Vaud'),
                ('Sergey', 'Vaud'),
                ('Valeyres-sous-Rances', 'Vaud'),
                ('Vallorbe', 'Vaud'),
                ('Vaulion', 'Vaud'),
                ('Vuiteboeuf', 'Vaud'),
                ('Corcelles-le-Jorat', 'Vaud'),
                ('Maracon', 'Vaud'),
                ('Montpreveyres', 'Vaud'),
                ('Ropraz', 'Vaud'),
                ('Servion', 'Vaud'),
                ('Vulliens', 'Vaud'),
                ('Jorat-Menthue', 'Vaud'),
                ('Oron', 'Vaud'),
                ('Jorat-Mézières', 'Vaud'),
                ('Champtauroz', 'Vaud'),
                ('Chevroux', 'Vaud'),
                ('Corcelles-près-Payerne', 'Vaud'),
                ('Grandcour', 'Vaud'),
                ('Henniez', 'Vaud'),
                ('Missy', 'Vaud'),
                ('Payerne', 'Vaud'),
                ('Trey', 'Vaud'),
                ('Treytorrens (Payerne)', 'Vaud'),
                ('Villarzel', 'Vaud'),
                ('Valbroye', 'Vaud'),
                ('Château-D''Oex', 'Vaud'),
                ('Rossinière', 'Vaud'),
                ('Rougemont', 'Vaud'),
                ('Allaman', 'Vaud'),
                ('Bursinel', 'Vaud'),
                ('Bursins', 'Vaud'),
                ('Burtigny', 'Vaud'),
                ('Dully', 'Vaud'),
                ('Essertines-sur-Rolle', 'Vaud'),
                ('Gilly', 'Vaud'),
                ('Luins', 'Vaud'),
                ('Mont-sur-Rolle', 'Vaud'),
                ('Perroy', 'Vaud'),
                ('Rolle', 'Vaud'),
                ('Tartegnin', 'Vaud'),
                ('Vinzel', 'Vaud'),
                ('L''Abbaye', 'Vaud'),
                ('Le Chenit', 'Vaud'),
                ('Le Lieu', 'Vaud'),
                ('Chardonne', 'Vaud'),
                ('Corseaux', 'Vaud'),
                ('Corsier-sur-Vevey', 'Vaud'),
                ('Jongny', 'Vaud'),
                ('Montreux', 'Vaud'),
                ('La Tour-de-Peilz', 'Vaud'),
                ('Vevey', 'Vaud'),
                ('Veytaux', 'Vaud'),
                ('Blonay - Saint-Légier', 'Vaud'),
                ('Belmont-sur-Yverdon', 'Vaud'),
                ('Bioley-Magnoux', 'Vaud'),
                ('Chamblon', 'Vaud'),
                ('Champvent', 'Vaud'),
                ('Chavannes-le-Chêne', 'Vaud'),
                ('Chêne-Pâquier', 'Vaud'),
                ('Cheseaux-Noréaz', 'Vaud'),
                ('Cronay', 'Vaud'),
                ('Cuarny', 'Vaud'),
                ('Démoret', 'Vaud'),
                ('Donneloye', 'Vaud'),
                ('Ependes (VD)', 'Vaud'),
                ('Mathod', 'Vaud'),
                ('Molondin', 'Vaud'),
                ('Montagny-près-Yverdon', 'Vaud'),
                ('Oppens', 'Vaud'),
                ('Orges', 'Vaud'),
                ('Orzens', 'Vaud'),
                ('Pomy', 'Vaud'),
                ('Rovray', 'Vaud'),
                ('Suchy', 'Vaud'),
                ('Suscévaz', 'Vaud'),
                ('Treycovagnes', 'Vaud'),
                ('Ursins', 'Vaud'),
                ('Valeyres-sous-Montagny', 'Vaud'),
                ('Valeyres-sous-Ursins', 'Vaud'),
                ('Villars-Epeney', 'Vaud'),
                ('Vugelles-La Mothe', 'Vaud'),
                ('Yverdon-les-Bains', 'Vaud'),
                ('Yvonand', 'Vaud'),
                ('Brig-Glis', 'Valais'),
                ('Eggerberg', 'Valais'),
                ('Naters', 'Valais'),
                ('Ried-Brig', 'Valais'),
                ('Simplon', 'Valais'),
                ('Termen', 'Valais'),
                ('Zwischbergen', 'Valais'),
                ('Ardon', 'Valais'),
                ('Chamoson', 'Valais'),
                ('Conthey', 'Valais'),
                ('Nendaz', 'Valais'),
                ('Vétroz', 'Valais'),
                ('Bourg-Saint-Pierre', 'Valais'),
                ('Liddes', 'Valais'),
                ('Orsières', 'Valais'),
                ('Sembrancher', 'Valais'),
                ('Val de Bagnes', 'Valais'),
                ('Bellwald', 'Valais'),
                ('Binn', 'Valais'),
                ('Ernen', 'Valais'),
                ('Fiesch', 'Valais'),
                ('Fieschertal', 'Valais'),
                ('Lax', 'Valais'),
                ('Obergoms', 'Valais'),
                ('Goms', 'Valais'),
                ('Ayent', 'Valais'),
                ('Evolène', 'Valais'),
                ('Hérémence', 'Valais'),
                ('Saint-Martin (VS)', 'Valais'),
                ('Vex', 'Valais'),
                ('Mont-Noble', 'Valais'),
                ('Agarn', 'Valais'),
                ('Albinen', 'Valais'),
                ('Ergisch', 'Valais'),
                ('Inden', 'Valais'),
                ('Leuk', 'Valais'),
                ('Leukerbad', 'Valais'),
                ('Oberems', 'Valais'),
                ('Salgesch', 'Valais'),
                ('Varen', 'Valais'),
                ('Guttet-Feschel', 'Valais'),
                ('Gampel-Bratsch', 'Valais'),
                ('Turtmann-Unterems', 'Valais'),
                ('Bovernier', 'Valais'),
                ('Fully', 'Valais'),
                ('Isérables', 'Valais'),
                ('Leytron', 'Valais'),
                ('Martigny', 'Valais'),
                ('Martigny-Combe', 'Valais'),
                ('Riddes', 'Valais'),
                ('Saillon', 'Valais'),
                ('Saxon', 'Valais'),
                ('Trient', 'Valais'),
                ('Champéry', 'Valais'),
                ('Collombey-Muraz', 'Valais'),
                ('Monthey', 'Valais'),
                ('Port-Valais', 'Valais'),
                ('Saint-Gingolph', 'Valais'),
                ('Troistorrents', 'Valais'),
                ('Val-D''Illiez', 'Valais'),
                ('Vionnaz', 'Valais'),
                ('Vouvry', 'Valais'),
                ('Bister', 'Valais'),
                ('Bitsch', 'Valais'),
                ('Grengiols', 'Valais'),
                ('Riederalp', 'Valais'),
                ('Ausserberg', 'Valais'),
                ('Blatten', 'Valais'),
                ('Bürchen', 'Valais'),
                ('Eischoll', 'Valais'),
                ('Ferden', 'Valais'),
                ('Kippel', 'Valais'),
                ('Niedergesteln', 'Valais'),
                ('Raron', 'Valais'),
                ('Unterbäch', 'Valais'),
                ('Wiler (Lötschen)', 'Valais'),
                ('Mörel-Filet', 'Valais'),
                ('Steg-Hohtenn', 'Valais'),
                ('Bettmeralp', 'Valais'),
                ('Collonges', 'Valais'),
                ('Dorénaz', 'Valais'),
                ('Evionnaz', 'Valais'),
                ('Finhaut', 'Valais'),
                ('Massongex', 'Valais'),
                ('Saint-Maurice', 'Valais'),
                ('Salvan', 'Valais'),
                ('Vernayaz', 'Valais'),
                ('Vérossaz', 'Valais'),
                ('Chalais', 'Valais'),
                ('Chippis', 'Valais'),
                ('Grône', 'Valais'),
                ('Icogne', 'Valais'),
                ('Lens', 'Valais'),
                ('Saint-Léonard', 'Valais'),
                ('Sierre', 'Valais'),
                ('Anniviers', 'Valais'),
                ('Crans-Montana', 'Valais'),
                ('Noble-Contrée', 'Valais'),
                ('Arbaz', 'Valais'),
                ('Grimisuat', 'Valais'),
                ('Savièse', 'Valais'),
                ('Sion', 'Valais'),
                ('Veysonnaz', 'Valais'),
                ('Baltschieder', 'Valais'),
                ('Eisten', 'Valais'),
                ('Embd', 'Valais'),
                ('Grächen', 'Valais'),
                ('Lalden', 'Valais'),
                ('Randa', 'Valais'),
                ('Saas-Almagell', 'Valais'),
                ('Saas-Balen', 'Valais'),
                ('Saas-Fee', 'Valais'),
                ('Saas-Grund', 'Valais'),
                ('St. Niklaus', 'Valais'),
                ('Stalden (VS)', 'Valais'),
                ('Staldenried', 'Valais'),
                ('Täsch', 'Valais'),
                ('Törbel', 'Valais'),
                ('Visp', 'Valais'),
                ('Visperterminen', 'Valais'),
                ('Zeneggen', 'Valais'),
                ('Zermatt', 'Valais'),
                ('Boudry', 'Neuchâtel'),
                ('Cortaillod', 'Neuchâtel'),
                ('Rochefort', 'Neuchâtel'),
                ('Milvignes', 'Neuchâtel'),
                ('La Grande Béroche', 'Neuchâtel'),
                ('La Chaux-de-Fonds', 'Neuchâtel'),
                ('Les Planchettes', 'Neuchâtel'),
                ('La Sagne', 'Neuchâtel'),
                ('La Brévine', 'Neuchâtel'),
                ('Brot-Plamboz', 'Neuchâtel'),
                ('Le Cerneux-Péquignot', 'Neuchâtel'),
                ('La Chaux-du-Milieu', 'Neuchâtel'),
                ('Le Locle', 'Neuchâtel'),
                ('Les Ponts-de-Martel', 'Neuchâtel'),
                ('Cornaux', 'Neuchâtel'),
                ('Cressier (NE)', 'Neuchâtel'),
                ('Enges', 'Neuchâtel'),
                ('Hauterive (NE)', 'Neuchâtel'),
                ('Le Landeron', 'Neuchâtel'),
                ('Lignières', 'Neuchâtel'),
                ('Neuchâtel', 'Neuchâtel'),
                ('Saint-Blaise', 'Neuchâtel'),
                ('La Tène', 'Neuchâtel'),
                ('Val-de-Ruz', 'Neuchâtel'),
                ('La Côte-aux-Fées', 'Neuchâtel'),
                ('Les Verrières', 'Neuchâtel'),
                ('Val-de-Travers', 'Neuchâtel'),
                ('Aire-la-Ville', 'Genève'),
                ('Anières', 'Genève'),
                ('Avully', 'Genève'),
                ('Avusy', 'Genève'),
                ('Bardonnex', 'Genève'),
                ('Bellevue', 'Genève'),
                ('Bernex', 'Genève'),
                ('Carouge (GE)', 'Genève'),
                ('Cartigny', 'Genève'),
                ('Céligny', 'Genève'),
                ('Chancy', 'Genève'),
                ('Chêne-Bougeries', 'Genève'),
                ('Chêne-Bourg', 'Genève'),
                ('Choulex', 'Genève'),
                ('Collex-Bossy', 'Genève'),
                ('Collonge-Bellerive', 'Genève'),
                ('Cologny', 'Genève'),
                ('Confignon', 'Genève'),
                ('Corsier (GE)', 'Genève'),
                ('Dardagny', 'Genève'),
                ('Genève', 'Genève'),
                ('Genthod', 'Genève'),
                ('Le Grand-Saconnex', 'Genève'),
                ('Gy', 'Genève'),
                ('Hermance', 'Genève'),
                ('Jussy', 'Genève'),
                ('Laconnex', 'Genève'),
                ('Lancy', 'Genève'),
                ('Meinier', 'Genève'),
                ('Meyrin', 'Genève'),
                ('Onex', 'Genève'),
                ('Perly-Certoux', 'Genève'),
                ('Plan-les-Ouates', 'Genève'),
                ('Pregny-Chambésy', 'Genève'),
                ('Presinge', 'Genève'),
                ('Puplinge', 'Genève'),
                ('Russin', 'Genève'),
                ('Satigny', 'Genève'),
                ('Soral', 'Genève'),
                ('Thônex', 'Genève'),
                ('Troinex', 'Genève'),
                ('Vandoeuvres', 'Genève'),
                ('Vernier', 'Genève'),
                ('Versoix', 'Genève'),
                ('Veyrier', 'Genève'),
                ('Boécourt', 'Jura'),
                ('Bourrignon', 'Jura'),
                ('Châtillon (JU)', 'Jura'),
                ('Courchapoix', 'Jura'),
                ('Courrendlin', 'Jura'),
                ('Courroux', 'Jura'),
                ('Courtételle', 'Jura'),
                ('Delémont', 'Jura'),
                ('Develier', 'Jura'),
                ('Ederswiler', 'Jura'),
                ('Mervelier', 'Jura'),
                ('Mettembert', 'Jura'),
                ('Movelier', 'Jura'),
                ('Pleigne', 'Jura'),
                ('Rossemaison', 'Jura'),
                ('Saulcy', 'Jura'),
                ('Soyhières', 'Jura'),
                ('Haute-Sorne', 'Jura'),
                ('Val Terbi', 'Jura'),
                ('Le Bémont (JU)', 'Jura'),
                ('Les Bois', 'Jura'),
                ('Les Breuleux', 'Jura'),
                ('La Chaux-des-Breuleux', 'Jura'),
                ('Les Enfers', 'Jura'),
                ('Les Genevez (JU)', 'Jura'),
                ('Lajoux (JU)', 'Jura'),
                ('Montfaucon', 'Jura'),
                ('Muriaux', 'Jura'),
                ('Le Noirmont', 'Jura'),
                ('Saignelégier', 'Jura'),
                ('Saint-Brais', 'Jura'),
                ('Soubey', 'Jura'),
                ('Alle', 'Jura'),
                ('Beurnevésin', 'Jura'),
                ('Boncourt', 'Jura'),
                ('Bonfol', 'Jura'),
                ('Bure', 'Jura'),
                ('Coeuve', 'Jura'),
                ('Cornol', 'Jura'),
                ('Courchavon', 'Jura'),
                ('Courgenay', 'Jura'),
                ('Courtedoux', 'Jura'),
                ('Damphreux', 'Jura'),
                ('Fahy', 'Jura'),
                ('Fontenais', 'Jura'),
                ('Grandfontaine', 'Jura'),
                ('Lugnez', 'Jura'),
                ('Porrentruy', 'Jura'),
                ('Vendlincourt', 'Jura'),
                ('Basse-Allaine', 'Jura'),
                ('Clos du Doubs', 'Jura'),
                ('Haute-Ajoie', 'Jura'),
                ('La Baroche', 'Jura')
     ) AS m (name, state)
         JOIN state ON state.name = m.state;