INSERT INTO digilog.municipality (name_de, url, state_id)
SELECT m.name as name_de, m.url as url, state.id as state_id
FROM ( 
	VALUES 	('Citta'' Umilissima', 'http://www.cityofvalletta.org/', 'Malta'),
			('Citta'' Vittoriosa', 'http://birgu.gov.mt/', 'Malta'),
			('Citta'' Invicta', 'http://www.islalocalcouncil.com/', 'Malta'),
			('Citta'' Cospicua', 'nan', 'Malta'),
			('Citta'' Hompesch', 'http://www.zabbar.gov.mt/', 'Malta'),
			('Fgura', 'http://fgura.lc.gov.mt/', 'Malta'),
			('Floriana', 'http://www.florianalocalcouncil.com', 'Malta'),
			('Kalkara', 'http://www.lc.gov.mt/Page.aspx?catid=31&pid=184&lid=1', 'Malta'),
			('Luqa', 'http://maltairport.com', 'Malta'),
			('Marsa', 'http://www.lc.gov.mt/Page.aspx?catid=27&pid=184', 'Malta'),
			('Paola', 'http://www.paolalocalcouncil.org/', 'Malta'),
			('Santa Luċija', 'http://www.santalucija.gov.mt/', 'Malta'),
			('Tarxien', 'nan', 'Malta'),
			('Xgħajra', 'http://lc.gov.mt/Page.aspx?catid=79&pid=184&lid=1', 'Malta'),
			('Citta'' Pinto', 'http://www.qormilocalcouncil.com/', 'Malta'),
			('Birkirkara', 'https://localgovernment.gov.mt/en/lc/Birkirkara/Pages/default.aspx', 'Malta'),
			('Gżira', 'https://web.archive.org/web/20170305085553/http://gzira.gov.mt/', 'Malta'),
			('Ħamrun', 'https://hamrunspartansfc.com/', 'Malta'),
			('Msida', 'nan', 'Malta'),
			('Pembroke', 'http://www.pembroke.gov.mt/', 'Malta'),
			('Pieta''', 'https://localgovernment.gov.mt/en/lc/TalPieta/Pages/default.aspx', 'Malta'),
			('San Ġiljan', 'http://www.lc.gov.mt/Page.aspx?catid=50&pid=184&lid=1', 'Malta'),
			('San Ġwann', 'http://www.sangwannmalta.org/', 'Malta'),
			('Santa Venera', 'http://lc.gov.mt/Page.aspx?catid=51&pid=184&lid=1', 'Malta'),
			('Sliema', 'http://sliemalocalcouncil.com/', 'Malta'),
			('Swieqi', 'http://swieqi.eu/', 'Malta'),
			('Ta'' Xbiex', 'https://archive.today/20121208220529/http://www.taxbiex.com/', 'Malta'),
			('Citta'' Beland', 'nan', 'Malta'),
			('Birżebbuġa', 'http://www.birzebbugalc.com/', 'Malta'),
			('Gudja', 'nan', 'Malta'),
			('Għaxaq', 'http://lc.gov.mt/Page.aspx?catid=35&pid=184&lid=1', 'Malta'),
			('Kirkop', 'nan', 'Malta'),
			('Marsaskala', 'http://marsaskala.lc.com.mt/', 'Malta'),
			('Marsaxlokk', 'http://en.marsaxlokklc.com/', 'Malta'),
			('Mqabba', 'http://www.mqabba.gov.mt/', 'Malta'),
			('Qrendi', 'http://qrendilocalcouncil.org.mt', 'Malta'),
			('Safi', 'http://www.lc.gov.mt/Page.aspx?catid=74&pid=184&lid=1', 'Malta'),
			('Żurrieq', 'http://zurrieqlocalcouncil.com/', 'Malta'),
			('Citta'' Notabile', 'https://localgovernment.gov.mt/en/lc/Mdina/Pages/default.aspx', 'Malta'),
			('Citta'' Rohan', 'nan', 'Malta'),
			('Citta'' Ferdinand', 'nan', 'Malta'),
			('Attard', 'https://localgovernment.gov.mt/en/lc/Attard/Pages/default.aspx', 'Malta'),
			('Balzan', 'http://halbalzanlocalcouncil.com/', 'Malta'),
			('Dingli', 'http://www.dingli.gov.mt/', 'Malta'),
			('Iklin', 'http://lc.gov.mt/Page.aspx?catid=15&pid=184', 'Malta'),
			('Lija', 'http://lc.gov.mt/Page.aspx?catid=16&pid=184&lid=1', 'Malta'),
			('Rabat (Malta)', 'nan', 'Malta'),
			('Mtarfa', 'http://lc.gov.mt/Page.aspx?catid=21&pid=184&lid=1', 'Malta'),
			('Għargħur', 'http://gharghur.gov.mt/', 'Malta'),
			('Mellieħa', 'http://mellieha.gov.mt/', 'Malta'),
			('Mġarr', 'http://mgarrlc.com/', 'Malta'),
			('Mosta', 'http://www.mostalocalcouncil.com/', 'Malta'),
			('Naxxar', 'http://www.naxxar.com/', 'Malta'),
			('San Pawl Il-Baħar', 'http://sanpawllocalcouncil.com/', 'Malta'),
			('Citta'' Victoria', 'nan', 'Malta'),
			('Fontana', 'http://lc.gov.mt/Page.aspx?catid=40&pid=184&lid=1', 'Malta'),
			('Għajnsielem and Comino', 'nan', 'Malta'),
			('Għarb', 'https://www.gharbnet.com/', 'Malta'),
			('Għasri', 'http://www.ghasri.com/', 'Malta'),
			('Kerċem', 'http://www.kercemgozo.com/', 'Malta'),
			('Munxar', 'http://www.munxar.gov.mt/', 'Malta'),
			('Nadur', 'http://www.nadur.gov.mt/', 'Malta'),
			('Qala', 'http://lc.gov.mt/Page.aspx?catid=82&pid=184&lid=1', 'Malta'),
			('San Lawrenz', 'http://www.sanlawrenz.gov.mt/', 'Malta'),
			('Sannat', 'http://lc.gov.mt/Page.aspx?catid=85&pid=184&lid=1', 'Malta'),
			('Xagħra', 'http://www.xaghra.com/article/?lang=en', 'Malta'),
			('Xewkija', 'http://www.xewkija.gov.mt/', 'Malta'),
			('Żebbuġ (Gozo)', 'http://www.zebbuggozo.com/', 'Malta')
	) AS m (name, url, country)
		JOIN country ON country.name_en = 'Malta'
		JOIN state ON country.code = state.country_code;