name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: "scrapy: tags"
      id: scrapy-meta
      uses: docker/metadata-action@v4
      with:
        images: |
          trephor/digilog-scrapy
        tags: |
          type=ref,event=branch
          type=sha
    - name: "scrapy: Build and push"
      uses: docker/build-push-action@v2
      with:
        context: ./scrapy/.
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.scrapy-meta.outputs.tags }}
        labels: ${{ steps.scrapy-meta.outputs.labels }}
    - name: "web: tags"
      id: web-meta
      uses: docker/metadata-action@v4
      with:
        images: |
          trephor/digilog-web
        tags: |
          type=ref,event=branch
          type=sha
    - name: "web: Build and push"
      uses: docker/build-push-action@v2
      with:
        context: ./web/.
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.web-meta.outputs.tags }}
        labels: ${{ steps.web-meta.outputs.labels }}
    - name: "flyway: tags"
      id: flyway-meta
      uses: docker/metadata-action@v4
      with:
        images: |
          trephor/digilog-flyway
        tags: |
          type=ref,event=branch
          type=sha
    - name: "flyway: Build and push"
      uses: docker/build-push-action@v2
      with:
        context: ./flyway/.
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.flyway-meta.outputs.tags }}
        labels: ${{ steps.flyway-meta.outputs.labels }}
